const fs = require("fs");
const path = require("path");
const base = path.join("c:", "dev", "HMS", "patient_service", "src", "main", "java", "kr", "co", "hospital", "patients", "patient");
const implPath = path.join(base, "service", "PatientServiceImpl.java");
let c = fs.readFileSync(implPath, "utf8");
c = c.replace(/PatientFamilyCreateReqDTO/g, "FamilyCreateReqDTO");
c = c.replace(/PatientFamilyService/g, "FamilyRepository");
c = c.replace(/PatientFamilyResDTO/g, "FamilyResDTO");
c = c.replace(/PatientInfoHistoryEntity/g, "InfoHistoryEntity");
c = c.replace(/PatientInfoHistoryRepository/g, "InfoHistoryRepository");
c = c.replace(/PatientStatusHistoryEntity/g, "StatusHistoryEntity");
c = c.replace(/PatientStatusHistoryRepository/g, "StatusHistoryRepository");
c = c.replace(/patientFamilyService/g, "familyRepository");
c = c.replace(/patientStatusHistoryRepository/g, "statusHistoryRepository");
c = c.replace(/patientInfoHistoryRepository/g, "infoHistoryRepository");
c = c.replace(/patientFamilyService\.findByPatientId\(id\)/g, "findFamiliesByPatientId(id)");
c = c.replace(/patientFamilyService\.createForPatient\(saved\.getPatientId\(\), createreqDTO\.getFamilies\(\)\)/g, "createFamiliesForPatient(saved.getPatientId(), createreqDTO.getFamilies())");
const helper = "    private List<FamilyResDTO> findFamiliesByPatientId(Long patientId) {\n        return familyRepository.findAllByPatientIdOrderBySortOrderAsc(patientId).stream().map(this::familyToDTO).toList();\n    }\n    private List<FamilyResDTO> createFamiliesForPatient(Long patientId, List<FamilyCreateReqDTO> families) {\n        if (families == null || families.isEmpty()) return List.of();\n        List<FamilyResDTO> result = new java.util.ArrayList<>();\n        int order = 0;\n        for (FamilyCreateReqDTO dto : families) {\n            var entity = new kr.co.hospital.patients.patient.entity.FamilyEntity();\n            entity.setPatientId(patientId);\n            entity.setRelation(dto.getRelation() != null ? dto.getRelation().trim() : \"\");\n            entity.setFamilyName(dto.getFamilyName() != null ? dto.getFamilyName().trim() : \"\");\n            entity.setFamilyPhone(dto.getFamilyPhone() != null && !dto.getFamilyPhone().isBlank() ? dto.getFamilyPhone().trim() : null);\n            entity.setBirthDate(dto.getBirthDate());\n            entity.setIsPrimary(Boolean.TRUE.equals(dto.getIsPrimary()));\n            entity.setSortOrder(++order);\n            result.add(familyToDTO(familyRepository.save(entity)));\n        }\n        return result;\n    }\n    private FamilyResDTO familyToDTO(kr.co.hospital.patients.patient.entity.FamilyEntity e) {\n        return new FamilyResDTO(e.getFamilyId(), e.getPatientId(), e.getRelation(), e.getFamilyName(), e.getFamilyPhone(), e.getBirthDate(), e.getIsPrimary(), e.getSortOrder());\n    }\n\n";
c = c.replace("    private String trimToNull(String value) {", helper + "    private String trimToNull(String value) {");
c = c.replace("private final FamilyRepository familyRepository;", "private final FamilyRepository familyRepository;\n    " + "");
c = c.replace("import kr.co.hospital.patients.patient.service.FamilyRepository;", "import kr.co.hospital.patients.patient.repository.FamilyRepository;");
fs.writeFileSync(implPath, c, "utf8");
const svcPath = path.join(base, "service", "PatientService.java");
let s = fs.readFileSync(svcPath, "utf8");
s = s.replace(/PatientFamilyCreateReqDTO/g, "FamilyCreateReqDTO");
s = s.replace(/PatientFamilyResDTO/g, "FamilyResDTO");
fs.writeFileSync(svcPath, s, "utf8");
const ctrlPath = path.join(base, "controller", "FamilyController.java");
let f = fs.readFileSync(ctrlPath, "utf8");
f = f.replace(/PatientFamilyController/g, "FamilyController");
f = f.replace(/PatientFamilyService/g, "PatientService");
f = f.replace(/PatientFamilyCreateReqDTO/g, "FamilyCreateReqDTO");
f = f.replace(/PatientFamilyResDTO/g, "FamilyResDTO");
f = f.replace(/private final PatientService service;/g, "private final PatientService patientService;");
f = f.replace(/service\.findByPatientId/g, "patientService.findByPatientId");
f = f.replace(/service\.createForPatient/g, "patientService.createForPatient");
fs.writeFileSync(ctrlPath, f, "utf8");
console.log("Done");