ALTER TABLE CHJ.NURSING_RECORD ADD (
    RECEPTION_ID NUMBER(19)
);

UPDATE CHJ.NURSING_RECORD nr
SET nr.RECEPTION_ID = (
    SELECT cv.RECEPTION_ID
    FROM HOSPITAL.CLINICAL_VISIT cv
    WHERE TO_CHAR(cv.VISIT_ID) = nr.VISIT_ID
)
WHERE nr.VISIT_ID IS NOT NULL;

COMMIT;

CREATE INDEX CHJ.IDX_NR_RECEPTION_ID
    ON CHJ.NURSING_RECORD (RECEPTION_ID);

ALTER TABLE CHJ.NURSING_RECORD DROP COLUMN VISIT_ID;
