WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

DECLARE
    v_count NUMBER;

    PROCEDURE ensure_user(p_username IN VARCHAR2, p_password IN VARCHAR2) IS
    BEGIN
        SELECT COUNT(*)
          INTO v_count
          FROM ALL_USERS
         WHERE USERNAME = UPPER(p_username);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'CREATE USER ' || p_username || ' IDENTIFIED BY "' || p_password || '"';
        END IF;

        EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER TO ' || p_username;
        EXECUTE IMMEDIATE 'ALTER USER ' || p_username || ' QUOTA UNLIMITED ON USERS';
    END;
BEGIN
    ensure_user('CMH', '1111');
    ensure_user('HOSPITAL', '1111');
END;
/

BEGIN
    FOR current_table IN (
        SELECT TABLE_NAME
          FROM ALL_TABLES
         WHERE OWNER = 'CMH'
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE CMH.' || current_table.TABLE_NAME || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

BEGIN
    FOR current_sequence IN (
        SELECT SEQUENCE_NAME
          FROM ALL_SEQUENCES
         WHERE SEQUENCE_OWNER = 'CMH'
    ) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE CMH.' || current_sequence.SEQUENCE_NAME;
    END LOOP;
END;
/

BEGIN
    FOR current_table IN (
        SELECT TABLE_NAME
          FROM ALL_TABLES
         WHERE OWNER = 'HOSPITAL'
           AND TABLE_NAME = 'MENU'
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE HOSPITAL.' || current_table.TABLE_NAME || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

CREATE TABLE CMH.AUTH_ROLE (
    ROLE_CODE VARCHAR2(50) NOT NULL,
    ROLE_NAME VARCHAR2(100) NOT NULL,
    IS_ACTIVE CHAR(1) NOT NULL,
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE,
    CONSTRAINT PK_AUTH_ROLE PRIMARY KEY (ROLE_CODE),
    CONSTRAINT CK_AUTH_ROLE_IS_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE TABLE CMH.AUTH_USER (
    ID VARCHAR2(20) NOT NULL,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD_HASH VARCHAR2(100) NOT NULL,
    ROLE_CODE VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_AUTH_USER PRIMARY KEY (ID),
    CONSTRAINT UQ_AUTH_USER_USERNAME UNIQUE (USERNAME),
    CONSTRAINT FK_AUTH_USER_ROLE_CODE FOREIGN KEY (ROLE_CODE) REFERENCES CMH.AUTH_ROLE (ROLE_CODE)
);

CREATE TABLE CMH.MENU (
    MENU_ID NUMBER NOT NULL,
    PARENT_ID NUMBER,
    CODE VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    PATH VARCHAR2(200),
    ICON VARCHAR2(50),
    SORT_ORDER NUMBER NOT NULL,
    IS_ACTIVE CHAR(1) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT PK_CMH_MENU PRIMARY KEY (MENU_ID),
    CONSTRAINT CK_CMH_MENU_IS_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE TABLE CMH.AUTH_ROLE_MENU_PERMISSION (
    ROLE_CODE VARCHAR2(50) NOT NULL,
    MENU_ID NUMBER NOT NULL,
    CAN_VIEW CHAR(1) NOT NULL,
    CAN_CREATE CHAR(1) NOT NULL,
    CAN_UPDATE CHAR(1) NOT NULL,
    CAN_DELETE CHAR(1) NOT NULL,
    CONSTRAINT PK_AUTH_ROLE_MENU_PERMISSION PRIMARY KEY (ROLE_CODE, MENU_ID),
    CONSTRAINT FK_ARMP_ROLE_CODE FOREIGN KEY (ROLE_CODE) REFERENCES CMH.AUTH_ROLE (ROLE_CODE),
    CONSTRAINT CK_ARMP_CAN_VIEW CHECK (CAN_VIEW IN ('Y', 'N')),
    CONSTRAINT CK_ARMP_CAN_CREATE CHECK (CAN_CREATE IN ('Y', 'N')),
    CONSTRAINT CK_ARMP_CAN_UPDATE CHECK (CAN_UPDATE IN ('Y', 'N')),
    CONSTRAINT CK_ARMP_CAN_DELETE CHECK (CAN_DELETE IN ('Y', 'N'))
);

CREATE TABLE CMH.AUTH_USER_MENU_PERMISSION (
    USER_ID VARCHAR2(20) NOT NULL,
    MENU_ID NUMBER NOT NULL,
    CAN_VIEW CHAR(1),
    CAN_CREATE CHAR(1),
    CAN_UPDATE CHAR(1),
    CAN_DELETE CHAR(1),
    CONSTRAINT PK_AUTH_USER_MENU_PERMISSION PRIMARY KEY (USER_ID, MENU_ID),
    CONSTRAINT FK_AUMP_USER_ID FOREIGN KEY (USER_ID) REFERENCES CMH.AUTH_USER (ID),
    CONSTRAINT FK_AUMP_MENU_ID FOREIGN KEY (MENU_ID) REFERENCES CMH.MENU (MENU_ID),
    CONSTRAINT CK_AUMP_CAN_VIEW CHECK (CAN_VIEW IN ('Y', 'N') OR CAN_VIEW IS NULL),
    CONSTRAINT CK_AUMP_CAN_CREATE CHECK (CAN_CREATE IN ('Y', 'N') OR CAN_CREATE IS NULL),
    CONSTRAINT CK_AUMP_CAN_UPDATE CHECK (CAN_UPDATE IN ('Y', 'N') OR CAN_UPDATE IS NULL),
    CONSTRAINT CK_AUMP_CAN_DELETE CHECK (CAN_DELETE IN ('Y', 'N') OR CAN_DELETE IS NULL)
);

CREATE TABLE CMH.AUTH_SESSION (
    SESSION_ID VARCHAR2(36) NOT NULL,
    USER_ID VARCHAR2(20) NOT NULL,
    ACCESS_TOKEN_JTI VARCHAR2(36),
    REFRESH_TOKEN_JTI VARCHAR2(36),
    LOGIN_AT DATE NOT NULL,
    LAST_ACCESS_AT DATE,
    EXPIRES_AT DATE NOT NULL,
    IS_REVOKED CHAR(1) NOT NULL,
    REVOKED_AT DATE,
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE,
    CONSTRAINT PK_AUTH_SESSION PRIMARY KEY (SESSION_ID),
    CONSTRAINT FK_AUTH_SESSION_USER_ID FOREIGN KEY (USER_ID) REFERENCES CMH.AUTH_USER (ID),
    CONSTRAINT CK_AUTH_SESSION_IS_REVOKED CHECK (IS_REVOKED IN ('Y', 'N'))
);

CREATE TABLE CMH.LOGIN_HISTORY (
    LOGIN_HISTORY_ID NUMBER NOT NULL,
    USER_ID VARCHAR2(20),
    USERNAME VARCHAR2(50) NOT NULL,
    LOGIN_RESULT VARCHAR2(20) NOT NULL,
    ATTEMPTED_AT DATE NOT NULL,
    CLIENT_IP VARCHAR2(64),
    FAILURE_REASON VARCHAR2(100),
    CONSTRAINT PK_LOGIN_HISTORY PRIMARY KEY (LOGIN_HISTORY_ID),
    CONSTRAINT FK_LOGIN_HISTORY_USER_ID FOREIGN KEY (USER_ID) REFERENCES CMH.AUTH_USER (ID)
);

CREATE TABLE HOSPITAL.MENU (
    MENU_ID NUMBER NOT NULL,
    PARENT_ID NUMBER,
    CODE VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    PATH VARCHAR2(200),
    ICON VARCHAR2(50),
    SORT_ORDER NUMBER NOT NULL,
    IS_ACTIVE CHAR(1) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT PK_HOSPITAL_MENU PRIMARY KEY (MENU_ID),
    CONSTRAINT CK_HOSPITAL_MENU_IS_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE SEQUENCE CMH.AUTH_USER_ID_SEQ START WITH 11 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CMH.LOGIN_HISTORY_SEQ START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;

INSERT INTO CMH.AUTH_ROLE (ROLE_CODE, ROLE_NAME, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES ('ADMIN', 'Administrator', 'Y', SYSDATE, SYSDATE);
INSERT INTO CMH.AUTH_ROLE (ROLE_CODE, ROLE_NAME, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES ('DOCTOR', 'Doctor', 'Y', SYSDATE, SYSDATE);
INSERT INTO CMH.AUTH_ROLE (ROLE_CODE, ROLE_NAME, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES ('NURSE', 'Nurse', 'Y', SYSDATE, SYSDATE);
INSERT INTO CMH.AUTH_ROLE (ROLE_CODE, ROLE_NAME, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES ('RECEPTION', 'Reception', 'Y', SYSDATE, SYSDATE);
INSERT INTO CMH.AUTH_ROLE (ROLE_CODE, ROLE_NAME, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES ('STAFF', 'Staff', 'Y', SYSDATE, SYSDATE);
INSERT INTO CMH.AUTH_ROLE (ROLE_CODE, ROLE_NAME, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES ('RADIOLOGY_TECH', 'Radiology Tech', 'Y', SYSDATE, SYSDATE);
INSERT INTO CMH.AUTH_ROLE (ROLE_CODE, ROLE_NAME, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES ('CLINICAL_LAB_TECH', 'Clinical Lab Tech', 'Y', SYSDATE, SYSDATE);
INSERT INTO CMH.AUTH_ROLE (ROLE_CODE, ROLE_NAME, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES ('PATHOLOGY_COORDINATOR', 'Pathology Coordinator', 'Y', SYSDATE, SYSDATE);
INSERT INTO CMH.AUTH_ROLE (ROLE_CODE, ROLE_NAME, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES ('ENDOSCOPY_COORDINATOR', 'Endoscopy Coordinator', 'Y', SYSDATE, SYSDATE);
INSERT INTO CMH.AUTH_ROLE (ROLE_CODE, ROLE_NAME, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES ('PHYSIOLOGY_TEST_COORDINATOR', 'Physiology Test Coordinator', 'Y', SYSDATE, SYSDATE);

INSERT INTO CMH.AUTH_USER (ID, USERNAME, PASSWORD_HASH, ROLE_CODE)
VALUES ('26-1001', '26-1001', '1111', 'DOCTOR');
INSERT INTO CMH.AUTH_USER (ID, USERNAME, PASSWORD_HASH, ROLE_CODE)
VALUES ('26-2001', '26-2001', '1111', 'NURSE');
INSERT INTO CMH.AUTH_USER (ID, USERNAME, PASSWORD_HASH, ROLE_CODE)
VALUES ('26-3001', '26-3001', '1111', 'RECEPTION');
INSERT INTO CMH.AUTH_USER (ID, USERNAME, PASSWORD_HASH, ROLE_CODE)
VALUES ('26-4001', '26-4001', '1111', 'RADIOLOGY_TECH');
INSERT INTO CMH.AUTH_USER (ID, USERNAME, PASSWORD_HASH, ROLE_CODE)
VALUES ('26-5001', '26-5001', '1111', 'CLINICAL_LAB_TECH');
INSERT INTO CMH.AUTH_USER (ID, USERNAME, PASSWORD_HASH, ROLE_CODE)
VALUES ('26-6001', '26-6001', '1111', 'ADMIN');

INSERT INTO HOSPITAL.MENU VALUES (1, NULL, 'HOME', 'Home', '/', 'Home', 0, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO HOSPITAL.MENU VALUES (1000, NULL, 'RECEPTION', 'Reception', '/reception', 'Home', 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO HOSPITAL.MENU VALUES (1001, 1000, 'RECEPTION_HOME', 'Reception Dashboard', '/reception', 'List', 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO HOSPITAL.MENU VALUES (1002, 1000, 'RECEPTION_RESERVATIONS', 'Reservation Reception', '/reception/reservations', 'List', 2, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO HOSPITAL.MENU VALUES (1100, NULL, 'BOARD', 'Board', '/board', 'Description', 2, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO HOSPITAL.MENU VALUES (1101, 1100, 'BOARD_NOTICE', 'Notice', '/board/notices', 'List', 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO HOSPITAL.MENU VALUES (1300, NULL, 'DOCTOR', 'Doctor', '/doctor', 'MedicalServices', 4, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO HOSPITAL.MENU VALUES (1302, 1300, 'DOCTOR_ENCOUNTERS', 'Doctor Workspace', '/doctor/encounters', 'List', 2, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO HOSPITAL.MENU VALUES (1400, NULL, 'NURSE', 'Nurse', '/nurse', 'MedicalServices', 5, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO HOSPITAL.MENU VALUES (1405, 1400, 'NURSE_SUPPORT', 'Nurse Support', '/nurse/support', 'List', 3, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO HOSPITAL.MENU VALUES (1406, 1400, 'NURSE_RECORD', 'Nurse Record', '/nurse/records', 'List', 4, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO HOSPITAL.MENU VALUES (1500, NULL, 'ADMIN', 'Admin', '/admin', 'FactCheck', 6, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO CMH.MENU (MENU_ID, PARENT_ID, CODE, NAME, PATH, ICON, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT MENU_ID,
       PARENT_ID,
       CODE,
       NAME,
       PATH,
       ICON,
       SORT_ORDER,
       CASE WHEN TO_CHAR(IS_ACTIVE) IN ('Y', '1') THEN 'Y' ELSE 'N' END,
       CREATED_AT,
       UPDATED_AT
FROM HOSPITAL.MENU;

ALTER TABLE CMH.AUTH_ROLE_MENU_PERMISSION
    ADD CONSTRAINT FK_ARMP_MENU_ID FOREIGN KEY (MENU_ID) REFERENCES CMH.MENU (MENU_ID);

INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('ADMIN', 1, 'Y', 'Y', 'Y', 'Y');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('ADMIN', 1000, 'Y', 'Y', 'Y', 'Y');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('ADMIN', 1100, 'Y', 'Y', 'Y', 'Y');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('ADMIN', 1300, 'Y', 'Y', 'Y', 'Y');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('ADMIN', 1400, 'Y', 'Y', 'Y', 'Y');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('ADMIN', 1500, 'Y', 'Y', 'Y', 'Y');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('DOCTOR', 1, 'Y', 'N', 'N', 'N');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('DOCTOR', 1300, 'Y', 'Y', 'Y', 'N');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('DOCTOR', 1302, 'Y', 'Y', 'Y', 'N');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('NURSE', 1, 'Y', 'N', 'N', 'N');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('NURSE', 1400, 'Y', 'Y', 'Y', 'N');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('NURSE', 1405, 'Y', 'Y', 'Y', 'N');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('NURSE', 1406, 'Y', 'Y', 'Y', 'N');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('RECEPTION', 1, 'Y', 'N', 'N', 'N');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('RECEPTION', 1000, 'Y', 'Y', 'Y', 'N');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('RECEPTION', 1001, 'Y', 'Y', 'Y', 'N');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('RECEPTION', 1002, 'Y', 'Y', 'Y', 'N');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('RADIOLOGY_TECH', 1400, 'Y', 'Y', 'Y', 'N');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('CLINICAL_LAB_TECH', 1400, 'Y', 'Y', 'Y', 'N');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('PATHOLOGY_COORDINATOR', 1400, 'Y', 'Y', 'Y', 'N');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('ENDOSCOPY_COORDINATOR', 1400, 'Y', 'Y', 'Y', 'N');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('PHYSIOLOGY_TEST_COORDINATOR', 1400, 'Y', 'Y', 'Y', 'N');
INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION VALUES ('STAFF', 1, 'Y', 'N', 'N', 'N');

INSERT INTO CMH.AUTH_SESSION VALUES ('seed-session-1', '26-6001', 'seed-jti-1', 'seed-refresh-jti-1', SYSDATE - 2, SYSDATE - 2, SYSDATE - 1, 'Y', SYSDATE - 1, SYSDATE - 2, SYSDATE - 1);

INSERT INTO CMH.LOGIN_HISTORY VALUES (1, '26-6001', '26-6001', 'SUCCESS', SYSDATE - 1, '127.0.0.1', NULL);
INSERT INTO CMH.LOGIN_HISTORY VALUES (2, NULL, 'unknown', 'FAIL', SYSDATE - 1 / 24, '127.0.0.1', 'AUTH_INVALID_CREDENTIALS');

GRANT SELECT, INSERT, UPDATE, DELETE ON CMH.AUTH_ROLE TO HOSPITAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON CMH.AUTH_USER TO HOSPITAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON CMH.MENU TO HOSPITAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON CMH.AUTH_ROLE_MENU_PERMISSION TO HOSPITAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON CMH.AUTH_USER_MENU_PERMISSION TO HOSPITAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON CMH.AUTH_SESSION TO HOSPITAL;
GRANT SELECT, INSERT, UPDATE, DELETE ON CMH.LOGIN_HISTORY TO HOSPITAL;
GRANT SELECT ON CMH.AUTH_USER_ID_SEQ TO HOSPITAL;
GRANT SELECT ON CMH.LOGIN_HISTORY_SEQ TO HOSPITAL;

COMMIT;
