/* MVP 기준: 부서는 더미 FK 대상, 공통 직원 + 의사 + 간호사만 우선 반영 */
DROP TABLE JCH.EMPLOYEE_NURSE CASCADE CONSTRAINTS;
DROP TABLE JCH.EMPLOYEE_DOCTOR CASCADE CONSTRAINTS;
DROP TABLE JCH.EMPLOYEE_PRIVATE CASCADE CONSTRAINTS;
DROP TABLE JCH.EMPLOYEE CASCADE CONSTRAINTS;

CREATE TABLE JCH.EMPLOYEE (
    STAFF_ID       VARCHAR2(30 BYTE)    NOT NULL,
    DEPT_ID        VARCHAR2(30 BYTE)    NOT NULL,
    REAL_NAME      VARCHAR2(100 BYTE)   NOT NULL,
    PHONE          VARCHAR2(50 BYTE)    NULL,
    EMAIL          VARCHAR2(100 BYTE)   NULL,
    BIRTH_DATE     VARCHAR2(6 BYTE)     NULL,
    GENDER_CODE    VARCHAR2(1 BYTE)     NULL,
    ZIP_CODE       VARCHAR2(20 BYTE)    NULL,
    ADDRESS1       VARCHAR2(255 BYTE)   NULL,
    ADDRESS2       VARCHAR2(255 BYTE)   NULL,
    STATUS         VARCHAR2(20 BYTE)    DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT     DATE                 DEFAULT SYSDATE NOT NULL,
    UPDATED_AT     DATE                 DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (STAFF_ID),
    CONSTRAINT CK_EMPLOYEE_BIRTH_DATE CHECK (BIRTH_DATE IS NULL OR REGEXP_LIKE(BIRTH_DATE, '^[0-9]{6}$')),
    CONSTRAINT CK_EMPLOYEE_GENDER_CODE CHECK (GENDER_CODE IS NULL OR GENDER_CODE IN ('1','2','3','4')),
    CONSTRAINT CK_EMPLOYEE_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE','LEAVE','RETIRE')),
    CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPT_ID) REFERENCES JCH.DEPARTMENT (DEPT_ID)
);

CREATE TABLE JCH.EMPLOYEE_PRIVATE (
    STAFF_ID       VARCHAR2(30 BYTE)    NOT NULL,
    RRN_FRONT      VARCHAR2(6 BYTE)     NULL,
    RRN_BACK       VARCHAR2(7 BYTE)     NULL,
    CONSTRAINT PK_EMPLOYEE_PRIVATE PRIMARY KEY (STAFF_ID),
    CONSTRAINT CK_EMP_PRIVATE_RRN_FRONT CHECK (RRN_FRONT IS NULL OR REGEXP_LIKE(RRN_FRONT, '^[0-9]{6}$')),
    CONSTRAINT CK_EMP_PRIVATE_RRN_BACK CHECK (RRN_BACK IS NULL OR REGEXP_LIKE(RRN_BACK, '^[0-9]{7}$')),
    CONSTRAINT FK_EMP_PRIVATE_EMPLOYEE FOREIGN KEY (STAFF_ID) REFERENCES JCH.EMPLOYEE (STAFF_ID)
);

CREATE TABLE JCH.EMPLOYEE_DOCTOR (
    STAFF_ID          VARCHAR2(30 BYTE)     NOT NULL,
    LICENSE_NO        VARCHAR2(50 BYTE)     NOT NULL,
    DOCTOR_TYPE       VARCHAR2(30 BYTE)     NOT NULL,
    SPECIALTY_ID      VARCHAR2(30 BYTE)     NULL,
    PROFILE_SUMMARY   VARCHAR2(200 BYTE)    NULL,
    DOCTOR_FILE_URL   VARCHAR2(1000 BYTE)   NULL,
    EDUCATION         VARCHAR2(1000 BYTE)   NULL,
    CAREER_DETAIL     VARCHAR2(1000 BYTE)   NULL,
    CREATED_AT        DATE                 DEFAULT SYSDATE NOT NULL,
    UPDATED_AT        DATE                 DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_EMPLOYEE_DOCTOR PRIMARY KEY (STAFF_ID),
    CONSTRAINT UK_EMPLOYEE_DOCTOR_LICENSE UNIQUE (LICENSE_NO),
    CONSTRAINT FK_EMPLOYEE_DOCTOR_STAFF FOREIGN KEY (STAFF_ID) REFERENCES JCH.EMPLOYEE (STAFF_ID)
);

CREATE TABLE JCH.EMPLOYEE_NURSE (
    STAFF_ID            VARCHAR2(30 BYTE)     NOT NULL,
    LICENSE_NO          VARCHAR2(50 BYTE)     NOT NULL,
    NURSE_TYPE          VARCHAR2(30 BYTE)     NOT NULL,
    SHIFT_TYPE          VARCHAR2(30 BYTE)     NULL,
    EMPLOYMENT_TYPE     VARCHAR2(30 BYTE)     NULL,
    NURSE_FILE_URL      VARCHAR2(1000 BYTE)   NULL,
    EDUCATION           VARCHAR2(1000 BYTE)   NULL,
    CAREER_DETAIL       VARCHAR2(1000 BYTE)   NULL,
    CREATED_AT          DATE                 DEFAULT SYSDATE NOT NULL,
    UPDATED_AT          DATE                 DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_EMPLOYEE_NURSE PRIMARY KEY (STAFF_ID),
    CONSTRAINT UK_EMPLOYEE_NURSE_LICENSE UNIQUE (LICENSE_NO),
    CONSTRAINT FK_EMPLOYEE_NURSE_STAFF FOREIGN KEY (STAFF_ID) REFERENCES JCH.EMPLOYEE (STAFF_ID)
);
