/*------------------------------------------------------------------------------
-- Object: LHS.PATIENT_INFO_HISTORY
------------------------------------------------------------------------------*/
DROP TABLE LHS.PATIENT_INFO_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE LHS.PATIENT_INFO_HISTORY (
  HISTORY_ID    NUMBER                 NOT NULL,
  PATIENT_ID    NUMBER                 NOT NULL,
  CHANGE_TYPE   VARCHAR2(20 BYTE)      NOT NULL,
  BEFORE_DATA   CLOB                       NULL,
  AFTER_DATA    CLOB                       NULL,
  CHANGED_BY    VARCHAR2(50 BYTE)          NULL,
  CHANGED_AT    DATE                  DEFAULT SYSDATE NOT NULL
)
LOB (BEFORE_DATA) STORE AS (
  TABLESPACE TEAM_DEV_TS
  ENABLE STORAGE IN ROW
  CHUNK 8192
  NOCACHE
  LOGGING
  STORAGE (
    INITIAL     64 K
    NEXT        1 M
    MINEXTENTS  1
    MAXEXTENTS  UNLIMITED
  )
)
LOB (AFTER_DATA) STORE AS (
  TABLESPACE TEAM_DEV_TS
  ENABLE STORAGE IN ROW
  CHUNK 8192
  NOCACHE
  LOGGING
  STORAGE (
    INITIAL     64 K
    NEXT        1 M
    MINEXTENTS  1
    MAXEXTENTS  UNLIMITED
  )
)
TABLESPACE TEAM_DEV_TS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE (
    INITIAL     64 K
    NEXT        1 M
    MINEXTENTS  1
    MAXEXTENTS  UNLIMITED
)
LOGGING
NOCACHE
MONITORING
NOPARALLEL;

DROP SEQUENCE LHS.PATIENT_INFO_HISTORY_SEQ;
CREATE SEQUENCE LHS.PATIENT_INFO_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

ALTER TABLE LHS.PATIENT_INFO_HISTORY ADD
(
    CONSTRAINT PK_PATIENT_INFO_HISTORY
    PRIMARY KEY ( HISTORY_ID )
        USING INDEX
        TABLESPACE TEAM_DEV_TS
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        STORAGE (
            INITIAL     64 K
            NEXT        1 M
            MINEXTENTS  1
            MAXEXTENTS  UNLIMITED
        )
);

ALTER TABLE LHS.PATIENT_INFO_HISTORY ADD
(
    CONSTRAINT FK_INFO_HISTORY_PATIENT
    FOREIGN KEY ( PATIENT_ID )
        REFERENCES LHS.PATIENT ( PATIENT_ID )
);

CREATE INDEX LHS.IDX_INFO_HISTORY_PATIENT
ON LHS.PATIENT_INFO_HISTORY (PATIENT_ID, CHANGED_AT)
TABLESPACE TEAM_DEV_TS
LOGGING
NOPARALLEL;