package com.app.medical_support.common.sequence;

public enum SequenceIdType {
    RECORD_ID,
    MEDICATION_RECORD_ID,
    TREATMENT_RESULT_ID,
    TEST_EXECUTION_ID,
    IMAGING_EXAM_ID,
    IMAGING_RESULT_ID,
    ENDOSCOPY_EXAM_ID,
    ENDOSCOPY_RESULT_ID,
    PATHOLOGY_EXAM_ID,
    PATHOLOGY_EXAM_RESULT_ID,
    PHYSIOLOGICAL_EXAM_ID,
    PHYSIOLOGICAL_EXAM_RESULT_ID,
    SPECIMEN_EXAM_ID,
    SPECIMEN_EXAM_RESULT_ID
}
