/*
  Reservation department cutover:
  - keep only HOSPITAL.RESERVATION.DEPT_ID (VARCHAR2(30))
  - remove HOSPITAL.RESERVATION.DEPARTMENT_ID
*/

SET SERVEROUTPUT ON
SET FEEDBACK ON
SET DEFINE OFF

PROMPT === PRECHECK ===
SELECT COUNT(*) AS reservation_rows FROM HOSPITAL.RESERVATION;
SELECT COUNT(*) AS dept_id_null_before FROM HOSPITAL.RESERVATION WHERE DEPT_ID IS NULL;
SELECT COUNT(*) AS mismatch_before
  FROM HOSPITAL.RESERVATION
 WHERE DEPARTMENT_ID IS NOT NULL
   AND NVL(DEPT_ID,'#') <> TRIM(TO_CHAR(DEPARTMENT_ID));

-- 1) Add DEPT_ID if missing
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt
    FROM ALL_TAB_COLUMNS
   WHERE OWNER = 'HOSPITAL'
     AND TABLE_NAME = 'RESERVATION'
     AND COLUMN_NAME = 'DEPT_ID';

  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.RESERVATION ADD (DEPT_ID VARCHAR2(30 BYTE))';
  END IF;
END;
/

-- 2) Backfill DEPT_ID from DEPARTMENT_ID
UPDATE HOSPITAL.RESERVATION
   SET DEPT_ID = NVL(DEPT_ID, TRIM(TO_CHAR(DEPARTMENT_ID)))
 WHERE DEPT_ID IS NULL
   AND DEPARTMENT_ID IS NOT NULL;

-- 3) Drop NOT NULL/CHECK constraints bound to DEPARTMENT_ID on RESERVATION
DECLARE
  CURSOR c_cons IS
    SELECT con.CONSTRAINT_NAME
      FROM ALL_CONS_COLUMNS col
      JOIN ALL_CONSTRAINTS con
        ON con.OWNER = col.OWNER
       AND con.CONSTRAINT_NAME = col.CONSTRAINT_NAME
     WHERE col.OWNER = 'HOSPITAL'
       AND col.TABLE_NAME = 'RESERVATION'
       AND col.COLUMN_NAME = 'DEPARTMENT_ID'
       AND con.CONSTRAINT_TYPE = 'C';
BEGIN
  FOR r IN c_cons LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.RESERVATION DROP CONSTRAINT ' || r.CONSTRAINT_NAME;
  END LOOP;
END;
/

-- 4) Enforce DEPT_ID NOT NULL (must be fully migrated)
DECLARE
  v_nulls NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_nulls FROM HOSPITAL.RESERVATION WHERE DEPT_ID IS NULL;

  IF v_nulls > 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'DEPT_ID still has NULL rows: ' || v_nulls);
  END IF;

  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.RESERVATION MODIFY (DEPT_ID VARCHAR2(30 BYTE) NOT NULL)';
  EXCEPTION
    WHEN OTHERS THEN
      -- ORA-01442: column to be modified to NOT NULL is already NOT NULL
      IF SQLCODE != -1442 THEN
        RAISE;
      END IF;
  END;
END;
/

-- 5) Drop old DEPARTMENT_ID column if it still exists
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt
    FROM ALL_TAB_COLUMNS
   WHERE OWNER = 'HOSPITAL'
     AND TABLE_NAME = 'RESERVATION'
     AND COLUMN_NAME = 'DEPARTMENT_ID';

  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.RESERVATION DROP COLUMN DEPARTMENT_ID';
  END IF;
END;
/

PROMPT === POSTCHECK ===
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
  FROM ALL_TAB_COLUMNS
 WHERE OWNER = 'HOSPITAL'
   AND TABLE_NAME = 'RESERVATION'
   AND COLUMN_NAME IN ('DEPARTMENT_ID', 'DEPT_ID')
 ORDER BY COLUMN_NAME;

SELECT COUNT(*) AS dept_id_null_after
  FROM HOSPITAL.RESERVATION
 WHERE DEPT_ID IS NULL;

COMMIT;
