/*
  Department/Doctor cutover:
  - switch key reference from DEPARTMENT_ID(number) to DEPT_ID(varchar2(30))
  - drop old DEPARTMENT_ID columns in HOSPITAL.DEPARTMENT and HOSPITAL.DOCTOR
*/

SET SERVEROUTPUT ON
SET FEEDBACK ON
SET DEFINE OFF

PROMPT === PRECHECK ===
SELECT COUNT(*) AS department_rows FROM HOSPITAL.DEPARTMENT;
SELECT COUNT(*) AS doctor_rows FROM HOSPITAL.DOCTOR;
SELECT COUNT(*) AS dept_null_before FROM HOSPITAL.DEPARTMENT WHERE DEPT_ID IS NULL;
SELECT COUNT(*) AS doctor_dept_null_before FROM HOSPITAL.DOCTOR WHERE DEPT_ID IS NULL;
SELECT COUNT(*) AS mismatch_dept_before
  FROM HOSPITAL.DEPARTMENT
 WHERE DEPARTMENT_ID IS NOT NULL
   AND NVL(DEPT_ID,'#') <> TRIM(TO_CHAR(DEPARTMENT_ID));
SELECT COUNT(*) AS mismatch_doc_before
  FROM HOSPITAL.DOCTOR
 WHERE DEPARTMENT_ID IS NOT NULL
   AND NVL(DEPT_ID,'#') <> TRIM(TO_CHAR(DEPARTMENT_ID));

-- 1) Ensure DEPT_ID columns exist
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt
    FROM ALL_TAB_COLUMNS
   WHERE OWNER='HOSPITAL' AND TABLE_NAME='DEPARTMENT' AND COLUMN_NAME='DEPT_ID';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.DEPARTMENT ADD (DEPT_ID VARCHAR2(30 BYTE))';
  END IF;

  SELECT COUNT(*) INTO v_cnt
    FROM ALL_TAB_COLUMNS
   WHERE OWNER='HOSPITAL' AND TABLE_NAME='DOCTOR' AND COLUMN_NAME='DEPT_ID';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.DOCTOR ADD (DEPT_ID VARCHAR2(30 BYTE))';
  END IF;
END;
/

-- 2) Backfill from DEPARTMENT_ID
UPDATE HOSPITAL.DEPARTMENT
   SET DEPT_ID = NVL(DEPT_ID, TRIM(TO_CHAR(DEPARTMENT_ID)))
 WHERE DEPT_ID IS NULL
   AND DEPARTMENT_ID IS NOT NULL;

UPDATE HOSPITAL.DOCTOR
   SET DEPT_ID = NVL(DEPT_ID, TRIM(TO_CHAR(DEPARTMENT_ID)))
 WHERE DEPT_ID IS NULL
   AND DEPARTMENT_ID IS NOT NULL;

-- 3) Validation before constraint switch
DECLARE
  v_nulls NUMBER;
  v_dups NUMBER;
  v_orphans NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_nulls FROM HOSPITAL.DEPARTMENT WHERE DEPT_ID IS NULL;
  IF v_nulls > 0 THEN
    RAISE_APPLICATION_ERROR(-20011, 'DEPARTMENT.DEPT_ID has NULL rows: ' || v_nulls);
  END IF;

  SELECT COUNT(*) INTO v_dups
    FROM (
      SELECT DEPT_ID
        FROM HOSPITAL.DEPARTMENT
       GROUP BY DEPT_ID
      HAVING COUNT(*) > 1
    );
  IF v_dups > 0 THEN
    RAISE_APPLICATION_ERROR(-20012, 'DEPARTMENT.DEPT_ID has duplicate keys: ' || v_dups);
  END IF;

  SELECT COUNT(*) INTO v_orphans
    FROM HOSPITAL.DOCTOR d
   WHERE d.DEPT_ID IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
         FROM HOSPITAL.DEPARTMENT p
        WHERE p.DEPT_ID = d.DEPT_ID
     );
  IF v_orphans > 0 THEN
    RAISE_APPLICATION_ERROR(-20013, 'DOCTOR.DEPT_ID has orphan values: ' || v_orphans);
  END IF;
END;
/

-- 4) Drop FK/check constraints bound to old DEPARTMENT_ID
DECLARE
  CURSOR c_fk_old IS
    SELECT con.CONSTRAINT_NAME
      FROM ALL_CONS_COLUMNS col
      JOIN ALL_CONSTRAINTS con
        ON con.OWNER = col.OWNER
       AND con.CONSTRAINT_NAME = col.CONSTRAINT_NAME
     WHERE col.OWNER='HOSPITAL'
       AND col.TABLE_NAME='DOCTOR'
       AND col.COLUMN_NAME='DEPARTMENT_ID'
       AND con.CONSTRAINT_TYPE='R';

  CURSOR c_chk_old IS
    SELECT col.TABLE_NAME, con.CONSTRAINT_NAME
      FROM ALL_CONS_COLUMNS col
      JOIN ALL_CONSTRAINTS con
        ON con.OWNER = col.OWNER
       AND con.CONSTRAINT_NAME = col.CONSTRAINT_NAME
     WHERE col.OWNER='HOSPITAL'
       AND col.TABLE_NAME IN ('DEPARTMENT','DOCTOR')
       AND col.COLUMN_NAME='DEPARTMENT_ID'
       AND con.CONSTRAINT_TYPE='C';
BEGIN
  FOR r IN c_fk_old LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.DOCTOR DROP CONSTRAINT ' || r.CONSTRAINT_NAME;
  END LOOP;

  FOR r IN c_chk_old LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.' || r.TABLE_NAME || ' DROP CONSTRAINT ' || r.CONSTRAINT_NAME;
  END LOOP;
END;
/

-- 5) Replace DEPARTMENT PK: DEPARTMENT_ID -> DEPT_ID
DECLARE
  v_pk_old NUMBER;
  v_pk_on_deptid NUMBER;
  v_pk_on_deptid_name VARCHAR2(128);
  v_pk_on_deptid_col NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_pk_on_deptid
    FROM ALL_CONSTRAINTS con
   WHERE con.OWNER='HOSPITAL'
     AND con.TABLE_NAME='DEPARTMENT'
     AND con.CONSTRAINT_TYPE='P'
     AND EXISTS (
       SELECT 1
         FROM ALL_CONS_COLUMNS col
        WHERE col.OWNER=con.OWNER
          AND col.CONSTRAINT_NAME=con.CONSTRAINT_NAME
          AND col.TABLE_NAME=con.TABLE_NAME
          AND col.COLUMN_NAME='DEPARTMENT_ID'
     );

  IF v_pk_on_deptid > 0 THEN
    SELECT con.CONSTRAINT_NAME INTO v_pk_on_deptid_name
      FROM ALL_CONSTRAINTS con
     WHERE con.OWNER='HOSPITAL'
       AND con.TABLE_NAME='DEPARTMENT'
       AND con.CONSTRAINT_TYPE='P'
       AND EXISTS (
         SELECT 1
           FROM ALL_CONS_COLUMNS col
          WHERE col.OWNER=con.OWNER
            AND col.CONSTRAINT_NAME=con.CONSTRAINT_NAME
            AND col.TABLE_NAME=con.TABLE_NAME
            AND col.COLUMN_NAME='DEPARTMENT_ID'
       )
       AND ROWNUM = 1;

    EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.DEPARTMENT DROP CONSTRAINT ' || v_pk_on_deptid_name;
  END IF;

  SELECT COUNT(*) INTO v_pk_old
    FROM ALL_CONSTRAINTS
   WHERE OWNER='HOSPITAL'
     AND TABLE_NAME='DEPARTMENT'
     AND CONSTRAINT_TYPE='P';

  IF v_pk_old = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.DEPARTMENT ADD CONSTRAINT PK_DEPARTMENT_DEPT_ID PRIMARY KEY (DEPT_ID)';
  END IF;
END;
/

-- 6) Add FK DOCTOR.DEPT_ID -> DEPARTMENT.DEPT_ID (if missing)
DECLARE
  v_fk_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_fk_cnt
    FROM ALL_CONSTRAINTS con
   WHERE con.OWNER='HOSPITAL'
     AND con.TABLE_NAME='DOCTOR'
     AND con.CONSTRAINT_TYPE='R'
     AND EXISTS (
       SELECT 1
         FROM ALL_CONS_COLUMNS col
        WHERE col.OWNER=con.OWNER
          AND col.CONSTRAINT_NAME=con.CONSTRAINT_NAME
          AND col.TABLE_NAME=con.TABLE_NAME
          AND col.COLUMN_NAME='DEPT_ID'
     );

  IF v_fk_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.DOCTOR ADD CONSTRAINT FK_DOCTOR_DEPT_ID FOREIGN KEY (DEPT_ID) REFERENCES HOSPITAL.DEPARTMENT (DEPT_ID)';
  END IF;
END;
/

-- 7) Preserve old nullability semantics for DOCTOR column
DECLARE
  v_old_nullable VARCHAR2(1);
  v_nulls NUMBER;
BEGIN
  BEGIN
    SELECT NULLABLE INTO v_old_nullable
      FROM ALL_TAB_COLUMNS
     WHERE OWNER='HOSPITAL'
       AND TABLE_NAME='DOCTOR'
       AND COLUMN_NAME='DEPARTMENT_ID';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      v_old_nullable := 'Y';
  END;

  IF v_old_nullable = 'N' THEN
    SELECT COUNT(*) INTO v_nulls FROM HOSPITAL.DOCTOR WHERE DEPT_ID IS NULL;
    IF v_nulls > 0 THEN
      RAISE_APPLICATION_ERROR(-20014, 'DOCTOR.DEPT_ID has NULL rows but old DEPARTMENT_ID was NOT NULL: ' || v_nulls);
    END IF;
    BEGIN
      EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.DOCTOR MODIFY (DEPT_ID VARCHAR2(30 BYTE) NOT NULL)';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -1442 THEN
          RAISE;
        END IF;
    END;
  END IF;
END;
/

-- 8) Drop old columns if exist
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt
    FROM ALL_TAB_COLUMNS
   WHERE OWNER='HOSPITAL' AND TABLE_NAME='DOCTOR' AND COLUMN_NAME='DEPARTMENT_ID';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.DOCTOR DROP COLUMN DEPARTMENT_ID';
  END IF;

  SELECT COUNT(*) INTO v_cnt
    FROM ALL_TAB_COLUMNS
   WHERE OWNER='HOSPITAL' AND TABLE_NAME='DEPARTMENT' AND COLUMN_NAME='DEPARTMENT_ID';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.DEPARTMENT DROP COLUMN DEPARTMENT_ID';
  END IF;
END;
/

PROMPT === POSTCHECK ===
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
  FROM ALL_TAB_COLUMNS
 WHERE OWNER='HOSPITAL'
   AND TABLE_NAME IN ('DEPARTMENT','DOCTOR')
   AND COLUMN_NAME IN ('DEPARTMENT_ID','DEPT_ID')
 ORDER BY TABLE_NAME, COLUMN_NAME;

SELECT c.TABLE_NAME, c.COLUMN_NAME, con.CONSTRAINT_NAME, con.CONSTRAINT_TYPE
  FROM ALL_CONS_COLUMNS c
  JOIN ALL_CONSTRAINTS con
    ON con.OWNER=c.OWNER
   AND con.CONSTRAINT_NAME=c.CONSTRAINT_NAME
 WHERE c.OWNER='HOSPITAL'
   AND c.TABLE_NAME IN ('DEPARTMENT','DOCTOR')
   AND c.COLUMN_NAME IN ('DEPARTMENT_ID','DEPT_ID')
 ORDER BY c.TABLE_NAME, c.COLUMN_NAME, con.CONSTRAINT_NAME;

SELECT COUNT(*) AS doctor_dept_null_after FROM HOSPITAL.DOCTOR WHERE DEPT_ID IS NULL;

COMMIT;
