/*------------------------------------------------------------------------------
  紐⑹쟻:
    ?묒닔 ?꾨찓?몄쓽 吏꾨즺怨??ㅻ? NUMBER 湲곕컲 department_id ?먯꽌
    VARCHAR2(30) 湲곕컲 dept_id 濡??듭씪?쒕떎.

  ????ㅽ궎留?
    HOSPITAL

  ?곸슜 ??沅뚯옣:
    1) ?꾩껜 諛깆뾽
    2) ?몃옒??????쒓컙? ?곸슜
    3) ?꾨옒 寃利?荑쇰━ ?좎떎??------------------------------------------------------------------------------*/

-- 0) ?ъ쟾 ?뺤씤
SELECT COUNT(*) AS reception_rows FROM HOSPITAL.RECEPTION;
SELECT COUNT(*) AS reservation_rows FROM HOSPITAL.RESERVATION;
SELECT COUNT(*) AS department_rows FROM HOSPITAL.DEPARTMENT;
SELECT COUNT(*) AS doctor_rows FROM HOSPITAL.DOCTOR;

-- 1) department_id -> dept_id 而щ읆 異붽? (?놁쓣 ?뚮쭔)
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt
    FROM ALL_TAB_COLUMNS
   WHERE OWNER = 'HOSPITAL'
     AND TABLE_NAME = 'RECEPTION'
     AND COLUMN_NAME = 'DEPT_ID';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.RECEPTION ADD (DEPT_ID VARCHAR2(30 BYTE))';
  END IF;
END;
/

DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt
    FROM ALL_TAB_COLUMNS
   WHERE OWNER = 'HOSPITAL'
     AND TABLE_NAME = 'RESERVATION'
     AND COLUMN_NAME = 'DEPT_ID';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.RESERVATION ADD (DEPT_ID VARCHAR2(30 BYTE))';
  END IF;
END;
/

DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt
    FROM ALL_TAB_COLUMNS
   WHERE OWNER = 'HOSPITAL'
     AND TABLE_NAME = 'DEPARTMENT'
     AND COLUMN_NAME = 'DEPT_ID';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.DEPARTMENT ADD (DEPT_ID VARCHAR2(30 BYTE))';
  END IF;
END;
/

DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt
    FROM ALL_TAB_COLUMNS
   WHERE OWNER = 'HOSPITAL'
     AND TABLE_NAME = 'DOCTOR'
     AND COLUMN_NAME = 'DEPT_ID';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.DOCTOR ADD (DEPT_ID VARCHAR2(30 BYTE))';
  END IF;
END;
/

-- 2) 諛깊븘 (湲곗〈 NUMBER ?ㅻ? 臾몄옄?대줈 ?닿?)
UPDATE HOSPITAL.RECEPTION
   SET DEPT_ID = NVL(DEPT_ID, TRIM(TO_CHAR(DEPARTMENT_ID)))
 WHERE DEPT_ID IS NULL
   AND DEPARTMENT_ID IS NOT NULL;

UPDATE HOSPITAL.RESERVATION
   SET DEPT_ID = NVL(DEPT_ID, TRIM(TO_CHAR(DEPARTMENT_ID)))
 WHERE DEPT_ID IS NULL
   AND DEPARTMENT_ID IS NOT NULL;

UPDATE HOSPITAL.DEPARTMENT
   SET DEPT_ID = NVL(DEPT_ID, TRIM(TO_CHAR(DEPARTMENT_ID)))
 WHERE DEPT_ID IS NULL
   AND DEPARTMENT_ID IS NOT NULL;

UPDATE HOSPITAL.DOCTOR
   SET DEPT_ID = NVL(DEPT_ID, TRIM(TO_CHAR(DEPARTMENT_ID)))
 WHERE DEPT_ID IS NULL
   AND DEPARTMENT_ID IS NOT NULL;

-- 3) ?대? dept_id媛 ?덈뒗 ?뚯씠釉붿? ??낆쓣 VARCHAR2(30)濡??듭씪
ALTER TABLE HOSPITAL.RECEPTION_WAITING_QUEUE MODIFY (DEPT_ID VARCHAR2(30 BYTE));
ALTER TABLE HOSPITAL.INPATIENT_ADMISSION MODIFY (DEPT_ID VARCHAR2(30 BYTE));
ALTER TABLE HOSPITAL.RESERVATION_BOOKING_RULE MODIFY (DEPT_ID VARCHAR2(30 BYTE));
ALTER TABLE HOSPITAL.RESERVATION_DOCTOR_SCHEDULE MODIFY (DEPT_ID VARCHAR2(30 BYTE));

-- 4) 데이터 정합성 검증
SELECT COUNT(*) AS reception_dept_null
  FROM HOSPITAL.RECEPTION
 WHERE DEPT_ID IS NULL;

SELECT COUNT(*) AS reservation_dept_null
  FROM HOSPITAL.RESERVATION
 WHERE DEPT_ID IS NULL;

SELECT COUNT(*) AS doctor_dept_null
  FROM HOSPITAL.DOCTOR
 WHERE DEPT_ID IS NULL;

SELECT COUNT(*) AS department_dept_null
  FROM HOSPITAL.DEPARTMENT
 WHERE DEPT_ID IS NULL;

-- 5) (?좏깮) 援?而щ읆 ?쒓굅: ?댁쁺 ?덉젙?????섑뻾
-- ALTER TABLE HOSPITAL.RECEPTION DROP COLUMN DEPARTMENT_ID;
-- ALTER TABLE HOSPITAL.RESERVATION DROP COLUMN DEPARTMENT_ID;
-- ALTER TABLE HOSPITAL.DOCTOR DROP COLUMN DEPARTMENT_ID;
-- ALTER TABLE HOSPITAL.DEPARTMENT DROP COLUMN DEPARTMENT_ID;

COMMIT;
