server:
  port: 8081
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/xepdb1
    username: HOSPITAL
    password: ${PASSWORD:-changeme}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

toss:
    secret-key: ${TOSS_SECRET_KEY}
    base-url: https://api.tosspayments.com
