-- Role-based menu permissions for local development.
-- Each role gets only the menus that fit the job enough for realistic testing.

DELETE FROM HOSPITAL.AUTH_USER_MENU_PERMISSION;
DELETE FROM HOSPITAL.AUTH_ROLE_MENU_PERMISSION;

INSERT INTO HOSPITAL.AUTH_ROLE_MENU_PERMISSION (
    ROLE_CODE,
    MENU_ID,
    CAN_VIEW,
    CAN_CREATE,
    CAN_UPDATE,
    CAN_DELETE
)
SELECT
    'ADMIN',
    MENU_ID,
    'Y',
    'Y',
    'Y',
    'Y'
FROM HOSPITAL.CMH_MENU
WHERE IS_ACTIVE = 'Y';

INSERT INTO HOSPITAL.AUTH_ROLE_MENU_PERMISSION (
    ROLE_CODE,
    MENU_ID,
    CAN_VIEW,
    CAN_CREATE,
    CAN_UPDATE,
    CAN_DELETE
)
SELECT
    'DOCTOR',
    MENU_ID,
    'Y',
    CASE WHEN MENU_ID IN (1300, 1400, 1404, 1406) THEN 'Y' ELSE 'N' END,
    CASE WHEN MENU_ID IN (1300, 1400, 1404, 1406) THEN 'Y' ELSE 'N' END,
    'N'
FROM HOSPITAL.CMH_MENU
WHERE MENU_ID IN (
    1,
    2, 5, 6, 1008,
    1000, 1001,
    1300,
    1400, 1401, 1404, 1406
);

INSERT INTO HOSPITAL.AUTH_ROLE_MENU_PERMISSION (
    ROLE_CODE,
    MENU_ID,
    CAN_VIEW,
    CAN_CREATE,
    CAN_UPDATE,
    CAN_DELETE
)
SELECT
    'NURSE',
    MENU_ID,
    'Y',
    CASE WHEN MENU_ID IN (1405) THEN 'Y' ELSE 'N' END,
    CASE WHEN MENU_ID IN (1405) THEN 'Y' ELSE 'N' END,
    'N'
FROM HOSPITAL.CMH_MENU
WHERE MENU_ID IN (
    1,
    2, 5,
    1000, 1001, 16,
    1300,
    1400, 1401, 1405
);

INSERT INTO HOSPITAL.AUTH_ROLE_MENU_PERMISSION (
    ROLE_CODE,
    MENU_ID,
    CAN_VIEW,
    CAN_CREATE,
    CAN_UPDATE,
    CAN_DELETE
)
SELECT
    'RECEPTION',
    MENU_ID,
    'Y',
    CASE WHEN MENU_ID IN (1007, 16, 1002, 13, 14) THEN 'Y' ELSE 'N' END,
    CASE WHEN MENU_ID IN (1007, 16, 1002, 13, 14, 6, 1008) THEN 'Y' ELSE 'N' END,
    'N'
FROM HOSPITAL.CMH_MENU
WHERE MENU_ID IN (
    1,
    2, 5, 6, 1007, 1008,
    1000, 1001, 16, 1002, 13, 14,
    1100, 1102, 1103
);

INSERT INTO HOSPITAL.AUTH_ROLE_MENU_PERMISSION (
    ROLE_CODE,
    MENU_ID,
    CAN_VIEW,
    CAN_CREATE,
    CAN_UPDATE,
    CAN_DELETE
)
SELECT
    'CLINICAL_LAB_TECH',
    MENU_ID,
    'Y',
    CASE WHEN MENU_ID IN (1406) THEN 'Y' ELSE 'N' END,
    CASE WHEN MENU_ID IN (1406) THEN 'Y' ELSE 'N' END,
    'N'
FROM HOSPITAL.CMH_MENU
WHERE MENU_ID IN (
    1,
    2, 5,
    1400, 1401, 1406
);

INSERT INTO HOSPITAL.AUTH_ROLE_MENU_PERMISSION (
    ROLE_CODE,
    MENU_ID,
    CAN_VIEW,
    CAN_CREATE,
    CAN_UPDATE,
    CAN_DELETE
)
SELECT
    'RADIOLOGY_TECH',
    MENU_ID,
    'Y',
    CASE WHEN MENU_ID IN (1404) THEN 'Y' ELSE 'N' END,
    CASE WHEN MENU_ID IN (1404) THEN 'Y' ELSE 'N' END,
    'N'
FROM HOSPITAL.CMH_MENU
WHERE MENU_ID IN (
    1,
    2, 5,
    1400, 1401, 1404
);

INSERT INTO HOSPITAL.AUTH_ROLE_MENU_PERMISSION (
    ROLE_CODE,
    MENU_ID,
    CAN_VIEW,
    CAN_CREATE,
    CAN_UPDATE,
    CAN_DELETE
)
SELECT
    ROLE_CODE,
    MENU_ID,
    'Y',
    CASE WHEN MENU_ID IN (1401, 1404, 1406) THEN 'Y' ELSE 'N' END,
    CASE WHEN MENU_ID IN (1401, 1404, 1406) THEN 'Y' ELSE 'N' END,
    'N'
FROM (
    SELECT 'PATHOLOGY_COORDINATOR' AS ROLE_CODE FROM dual
    UNION ALL
    SELECT 'PHYSIOLOGY_TEST_COORDINATOR' FROM dual
    UNION ALL
    SELECT 'ENDOSCOPY_COORDINATOR' FROM dual
) roles
CROSS JOIN HOSPITAL.CMH_MENU menus
WHERE menus.MENU_ID IN (
    1,
    2, 5,
    1400, 1401, 1404, 1406
);

INSERT INTO HOSPITAL.AUTH_ROLE_MENU_PERMISSION (
    ROLE_CODE,
    MENU_ID,
    CAN_VIEW,
    CAN_CREATE,
    CAN_UPDATE,
    CAN_DELETE
)
SELECT
    'STAFF',
    MENU_ID,
    'Y',
    CASE WHEN MENU_ID IN (1610, 1620) THEN 'Y' ELSE 'N' END,
    CASE WHEN MENU_ID IN (1610, 1620) THEN 'Y' ELSE 'N' END,
    'N'
FROM HOSPITAL.CMH_MENU
WHERE MENU_ID IN (
    1,
    1600, 1610, 1620, 1630
);

COMMIT;
