-- Small demo data for local development.
-- The fixed 910xxx ids make this script safe to run again.

DELETE FROM HOSPITAL.PAYMENT WHERE PAYMENT_ID = 910001;
DELETE FROM HOSPITAL.BILL_ITEM WHERE BILL_ITEM_ID IN (910001, 910002);
DELETE FROM HOSPITAL.BILL WHERE BILL_ID IN (910001, 910002);
DELETE FROM HOSPITAL.IMAGING_EXAM WHERE IMAGING_EXAM_ID = 'IM-DEMO-001';
DELETE FROM HOSPITAL.SPECIMEN_EXAM WHERE SPECIMEN_EXAM_ID = 'SP-DEMO-001';
DELETE FROM HOSPITAL.SUPPORT_TEST_EXECUTION WHERE TEST_EXECUTION_ID IN ('TE-DEMO-001', 'TE-DEMO-002');
DELETE FROM HOSPITAL.NOTE WHERE NOTE_ID IN (910001, 910002);
DELETE FROM HOSPITAL.CLINICAL_VISIT_QUEUE WHERE QUEUE_ID IN (910001, 910002);
DELETE FROM HOSPITAL.CLINICAL_VISIT WHERE VISIT_ID IN (910001, 910002);
DELETE FROM HOSPITAL.NURSING_RECORD WHERE RECORD_ID IN ('NR-DEMO-001', 'NR-DEMO-002');
DELETE FROM HOSPITAL.RECEPTION_WAITING_QUEUE WHERE WAITING_QUEUE_ID IN (910001, 910002);
DELETE FROM HOSPITAL.RECEPTION_OUTPATIENT_DETAIL WHERE OUTPATIENT_DETAIL_ID IN (910001, 910002);
DELETE FROM HOSPITAL.RECEPTION WHERE RECEPTION_ID IN (910001, 910002);
DELETE FROM HOSPITAL.PATIENT_INSURANCE WHERE INSURANCE_ID IN (910001, 910002);
DELETE FROM HOSPITAL.PATIENT WHERE PATIENT_ID IN (910001, 910002);

INSERT INTO HOSPITAL.PATIENT (
    PATIENT_ID, PATIENT_NO, NAME, BIRTH_DATE, PHONE, EMAIL, ADDRESS, ADDRESS_DETAIL,
    STATUS_CODE, IS_VIP, CREATED_AT, UPDATED_AT, IS_FOREIGNER, NOTE, GENDER, RRN,
    CREATED_BY, UPDATED_BY, ACTIVE_YN, BASE_ADDRESS, DETAIL_ADDRESS,
    PATIENT_BIRTH_DATE, PATIENT_GENDER, PATIENT_NAME, PATIENT_PHONE, PATIENT_STATUS, POSTAL_CODE
) VALUES (
    910001, 'P-DEMO-001', 'Demo Patient A', DATE '1990-03-15', '010-1111-2222', NULL,
    'Sejong-daero 1, Seoul', NULL, 'ACTIVE', 0, SYSDATE, SYSDATE, 0,
    'Demo patient with cold symptoms', 'M', NULL, 'demo-seed', 'demo-seed', 'Y',
    'Sejong-daero 1, Seoul', NULL, '1990-03-15', 'M', 'Demo Patient A',
    '010-1111-2222', 'ACTIVE', '04524'
);

INSERT INTO HOSPITAL.PATIENT (
    PATIENT_ID, PATIENT_NO, NAME, BIRTH_DATE, PHONE, EMAIL, ADDRESS, ADDRESS_DETAIL,
    STATUS_CODE, IS_VIP, CREATED_AT, UPDATED_AT, IS_FOREIGNER, NOTE, GENDER, RRN,
    CREATED_BY, UPDATED_BY, ACTIVE_YN, BASE_ADDRESS, DETAIL_ADDRESS,
    PATIENT_BIRTH_DATE, PATIENT_GENDER, PATIENT_NAME, PATIENT_PHONE, PATIENT_STATUS, POSTAL_CODE
) VALUES (
    910002, 'P-DEMO-002', 'Demo Patient B', DATE '1985-08-21', '010-3333-4444', NULL,
    'Yulgok-ro 2, Seoul', NULL, 'ACTIVE', 0, SYSDATE, SYSDATE, 0,
    'Demo patient for regular checkup', 'F', NULL, 'demo-seed', 'demo-seed', 'Y',
    'Yulgok-ro 2, Seoul', NULL, '1985-08-21', 'F', 'Demo Patient B',
    '010-3333-4444', 'ACTIVE', '03149'
);

INSERT INTO HOSPITAL.PATIENT_INSURANCE (
    INSURANCE_ID, PATIENT_ID, INSURANCE_TYPE, POLICY_NO, START_DATE, END_DATE,
    ACTIVE_YN, CREATED_AT, UPDATED_AT, NOTE, VERIFIED_YN
) VALUES (
    910001, 910001, 'NATIONAL', 'NH-DEMO-001', SYSDATE - 365, NULL,
    1, SYSDATE, SYSDATE, 'Demo insurance record', 1
);

INSERT INTO HOSPITAL.PATIENT_INSURANCE (
    INSURANCE_ID, PATIENT_ID, INSURANCE_TYPE, POLICY_NO, START_DATE, END_DATE,
    ACTIVE_YN, CREATED_AT, UPDATED_AT, NOTE, VERIFIED_YN
) VALUES (
    910002, 910002, 'NATIONAL', 'NH-DEMO-002', SYSDATE - 365, NULL,
    1, SYSDATE, SYSDATE, 'Demo insurance record', 1
);

INSERT INTO HOSPITAL.RECEPTION (
    RECEPTION_ID, CREATED_AT, RECEPTION_NO, PATIENT_ID, VISIT_TYPE, DEPARTMENT_ID,
    DOCTOR_ID, RESERVATION_ID, SCHEDULED_AT, ARRIVED_AT, STATUS, NOTE, IS_ACTIVE,
    CREATED_BY, UPDATED_BY, UPDATED_AT, ACTIVE_YN, RECEPTION_STATUS, RECEPTION_TYPE, STAFF_ID
) VALUES (
    910001, SYSTIMESTAMP, 'R-DEMO-001', 910001, 'OUTPATIENT', 11,
    9001, NULL, SYSTIMESTAMP, SYSTIMESTAMP, 'WAITING', 'Demo outpatient reception', 1,
    'demo-seed', 'demo-seed', SYSTIMESTAMP, 'Y', 'WAITING', 'OUTPATIENT', NULL
);

INSERT INTO HOSPITAL.RECEPTION (
    RECEPTION_ID, CREATED_AT, RECEPTION_NO, PATIENT_ID, VISIT_TYPE, DEPARTMENT_ID,
    DOCTOR_ID, RESERVATION_ID, SCHEDULED_AT, ARRIVED_AT, STATUS, NOTE, IS_ACTIVE,
    CREATED_BY, UPDATED_BY, UPDATED_AT, ACTIVE_YN, RECEPTION_STATUS, RECEPTION_TYPE, STAFF_ID
) VALUES (
    910002, SYSTIMESTAMP, 'R-DEMO-002', 910002, 'OUTPATIENT', 18,
    9001, NULL, SYSTIMESTAMP, SYSTIMESTAMP, 'IN_PROGRESS', 'Demo outpatient reception', 1,
    'demo-seed', 'demo-seed', SYSTIMESTAMP, 'Y', 'IN_PROGRESS', 'OUTPATIENT', NULL
);

INSERT INTO HOSPITAL.RECEPTION_OUTPATIENT_DETAIL (
    OUTPATIENT_DETAIL_ID, RECEPTION_ID, RESERVATION_ID, VISIT_PURPOSE_CD, PRIMARY_SYMPTOM,
    CONSULTATION_TYPE_CD, INSURANCE_APPLY_YN, ACTIVE_YN, CREATED_AT, UPDATED_AT
) VALUES (
    910001, 910001, NULL, 'GENERAL', 'Cold symptoms', 'FIRST', 'Y', 'Y', SYSTIMESTAMP, SYSTIMESTAMP
);

INSERT INTO HOSPITAL.RECEPTION_OUTPATIENT_DETAIL (
    OUTPATIENT_DETAIL_ID, RECEPTION_ID, RESERVATION_ID, VISIT_PURPOSE_CD, PRIMARY_SYMPTOM,
    CONSULTATION_TYPE_CD, INSURANCE_APPLY_YN, ACTIVE_YN, CREATED_AT, UPDATED_AT
) VALUES (
    910002, 910002, NULL, 'CHECKUP', 'Regular checkup', 'FOLLOWUP', 'Y', 'Y', SYSTIMESTAMP, SYSTIMESTAMP
);

INSERT INTO HOSPITAL.RECEPTION_WAITING_QUEUE (
    WAITING_QUEUE_ID, RECEPTION_ID, QUEUE_NO, QUEUE_STATUS_CD, QUEUE_ORDER_NO,
    DEPT_ID, DOCTOR_ID, ESTIMATED_WAIT_MIN, ACTIVE_YN, CREATED_AT, UPDATED_AT
) VALUES (
    910001, 910001, 'W-DEMO-001', 'WAITING', 1, 11, 9001, 10, 'Y', SYSTIMESTAMP, SYSTIMESTAMP
);

INSERT INTO HOSPITAL.RECEPTION_WAITING_QUEUE (
    WAITING_QUEUE_ID, RECEPTION_ID, QUEUE_NO, QUEUE_STATUS_CD, QUEUE_ORDER_NO,
    DEPT_ID, DOCTOR_ID, ESTIMATED_WAIT_MIN, ACTIVE_YN, CREATED_AT, UPDATED_AT
) VALUES (
    910002, 910002, 'W-DEMO-002', 'WAITING', 2, 18, 9001, 15, 'Y', SYSTIMESTAMP, SYSTIMESTAMP
);

INSERT INTO HOSPITAL.NURSING_RECORD (
    RECORD_ID, SYSTOLIC_BP, DIASTOLIC_BP, PULSE, RESPIRATION, TEMPERATURE, SPO2,
    OBSERVATION, PAIN_SCORE, CONSCIOUSNESS_LEVEL, INITIAL_ASSESSMENT,
    PAST_MEDICAL_HISTORY, STATUS, CREATED_AT, UPDATED_AT, RECEPTION_ID,
    NURSING_ID, NURSE_NAME, HEIGHT_CM, WEIGHT_KG
) VALUES (
    'NR-DEMO-001', 120, 80, 72, 18, 37.2, 98, 'Demo vital sign record for first visit',
    2, 'ALERT', 'Demo initial assessment', 'No special history', 'ACTIVE',
    SYSTIMESTAMP, SYSTIMESTAMP, 910001, '26-6001', 'Demo Nurse', '170', '65'
);

INSERT INTO HOSPITAL.NURSING_RECORD (
    RECORD_ID, SYSTOLIC_BP, DIASTOLIC_BP, PULSE, RESPIRATION, TEMPERATURE, SPO2,
    OBSERVATION, PAIN_SCORE, CONSCIOUSNESS_LEVEL, INITIAL_ASSESSMENT,
    PAST_MEDICAL_HISTORY, STATUS, CREATED_AT, UPDATED_AT, RECEPTION_ID,
    NURSING_ID, NURSE_NAME, HEIGHT_CM, WEIGHT_KG
) VALUES (
    'NR-DEMO-002', 118, 76, 70, 17, 36.8, 99, 'Demo vital sign record before checkup',
    1, 'ALERT', 'Demo initial assessment', 'No special history', 'ACTIVE',
    SYSTIMESTAMP, SYSTIMESTAMP, 910002, '26-6001', 'Demo Nurse', '162', '54'
);

INSERT INTO HOSPITAL.CLINICAL_VISIT (
    VISIT_ID, PATIENT_ID, DOCTOR_ID, RECEPTION_ID, VISIT_STATUS, START_TIME, END_TIME, CREATED_AT, UPDATED_AT
) VALUES (
    910001, 910001, 9001, 910001, 'WAITING', SYSTIMESTAMP, NULL, SYSTIMESTAMP, SYSTIMESTAMP
);

INSERT INTO HOSPITAL.CLINICAL_VISIT (
    VISIT_ID, PATIENT_ID, DOCTOR_ID, RECEPTION_ID, VISIT_STATUS, START_TIME, END_TIME, CREATED_AT, UPDATED_AT
) VALUES (
    910002, 910002, 9001, 910002, 'IN_PROGRESS', SYSTIMESTAMP, NULL, SYSTIMESTAMP, SYSTIMESTAMP
);

INSERT INTO HOSPITAL.CLINICAL_VISIT_QUEUE (
    QUEUE_ID, VISIT_ID, QUEUE_ORDER, ROOM_ID, CREATED_AT
) VALUES (
    910001, 910001, 1, 101, SYSTIMESTAMP
);

INSERT INTO HOSPITAL.CLINICAL_VISIT_QUEUE (
    QUEUE_ID, VISIT_ID, QUEUE_ORDER, ROOM_ID, CREATED_AT
) VALUES (
    910002, 910002, 2, 101, SYSTIMESTAMP
);

INSERT INTO HOSPITAL.NOTE (
    NOTE_ID, VISIT_ID, CHIEF_COMPLAINT, PRESENT_ILLNESS, ASSESSMENT, PLAN,
    MEMO, STATUS, CREATED_AT, UPDATED_AT
) VALUES (
    910001, 910001, 'Cough and runny nose', 'Demo present illness',
    'Suspected upper respiratory infection', 'Follow-up observation',
    'Demo clinical note', 'ACTIVE', SYSTIMESTAMP, SYSTIMESTAMP
);

INSERT INTO HOSPITAL.NOTE (
    NOTE_ID, VISIT_ID, CHIEF_COMPLAINT, PRESENT_ILLNESS, ASSESSMENT, PLAN,
    MEMO, STATUS, CREATED_AT, UPDATED_AT
) VALUES (
    910002, 910002, 'Checkup consultation', 'Demo present illness',
    'No abnormal finding', 'Follow-up observation',
    'Demo clinical note', 'ACTIVE', SYSTIMESTAMP, SYSTIMESTAMP
);

INSERT INTO HOSPITAL.SUPPORT_TEST_EXECUTION (
    TEST_EXECUTION_ID, DETAIL_CODE, ORDER_ITEM_ID, EXECUTION_TYPE, STATUS, PROGRESS_STATUS,
    RETRY_NO, STARTED_AT, COMPLETED_AT, PERFORMER_ID, PERFORMER_NAME,
    PATIENT_ID, PATIENT_NAME, DEPARTMENT_NAME, CREATED_AT, UPDATED_AT
) VALUES (
    'TE-DEMO-001', 'LAB-CBC', NULL, 'SPECIMEN', 'REQUESTED', 'WAITING',
    0, SYSTIMESTAMP, NULL, '26-6001', 'Demo Technician',
    910001, 'Demo Patient A', 'Laboratory', SYSTIMESTAMP, SYSTIMESTAMP
);

INSERT INTO HOSPITAL.SUPPORT_TEST_EXECUTION (
    TEST_EXECUTION_ID, DETAIL_CODE, ORDER_ITEM_ID, EXECUTION_TYPE, STATUS, PROGRESS_STATUS,
    RETRY_NO, STARTED_AT, COMPLETED_AT, PERFORMER_ID, PERFORMER_NAME,
    PATIENT_ID, PATIENT_NAME, DEPARTMENT_NAME, CREATED_AT, UPDATED_AT
) VALUES (
    'TE-DEMO-002', 'IMG-XRAY', NULL, 'IMAGING', 'REQUESTED', 'WAITING',
    0, SYSTIMESTAMP, NULL, '26-6001', 'Demo Technician',
    910002, 'Demo Patient B', 'Radiology', SYSTIMESTAMP, SYSTIMESTAMP
);

INSERT INTO HOSPITAL.SPECIMEN_EXAM (
    SPECIMEN_EXAM_ID, TEST_EXECUTION_ID, SPECIMEN_TYPE, SPECIMEN_STATUS, COLLECTED_AT,
    COLLECTED_BY_ID, COLLECTION_SITE, RECOLLECTION_YN, STATUS, CREATED_AT, UPDATED_AT,
    DETAIL_CODE, PATIENT_ID, PATIENT_NAME, DEPARTMENT_NAME, PERFORMER_ID, PERFORMER_NAME, PROGRESS_STATUS
) VALUES (
    'SP-DEMO-001', 'TE-DEMO-001', 'BLOOD', 'COLLECTED', SYSTIMESTAMP,
    '26-6001', 'Left arm', 'N', 'REQUESTED', SYSTIMESTAMP, SYSTIMESTAMP,
    'LAB-CBC', 910001, 'Demo Patient A', 'Laboratory', '26-6001', 'Demo Technician', 'WAITING'
);

INSERT INTO HOSPITAL.IMAGING_EXAM (
    IMAGING_EXAM_ID, TEST_EXECUTION_ID, IMAGING_TYPE, DETAIL_CODE, PATIENT_ID,
    PATIENT_NAME, DEPARTMENT_NAME, STATUS, PROGRESS_STATUS, PERFORMER_ID,
    PERFORMER_NAME, CREATED_AT, UPDATED_AT
) VALUES (
    'IM-DEMO-001', 'TE-DEMO-002', 'XRAY', 'IMG-XRAY', 910002,
    'Demo Patient B', 'Radiology', 'REQUESTED', 'WAITING', '26-6001',
    'Demo Technician', SYSTIMESTAMP, SYSTIMESTAMP
);

INSERT INTO HOSPITAL.BILL (
    BILL_ID, CREATED_AT, BILLING_NO, PATIENT_ID, VISIT_ID, SOURCE_EVENT_ID,
    TREATMENT_DATE, TOTAL_AMOUNT, PAID_AMOUNT, REMAINING_AMOUNT, STATUS
) VALUES (
    910001, SYSTIMESTAMP, 'B-DEMO-001', 910001, 910001, 'DEMO-SEED',
    SYSTIMESTAMP, 15000, 0, 15000, 'READY'
);

INSERT INTO HOSPITAL.BILL (
    BILL_ID, CREATED_AT, BILLING_NO, PATIENT_ID, VISIT_ID, SOURCE_EVENT_ID,
    TREATMENT_DATE, TOTAL_AMOUNT, PAID_AMOUNT, REMAINING_AMOUNT, STATUS
) VALUES (
    910002, SYSTIMESTAMP, 'B-DEMO-002', 910002, 910002, 'DEMO-SEED',
    SYSTIMESTAMP, 30000, 10000, 20000, 'CONFIRMED'
);

INSERT INTO HOSPITAL.BILL_ITEM (
    BILL_ITEM_ID, BILL_ID, ITEM_NAME, ITEM_AMOUNT
) VALUES (
    910001, 910001, 'Outpatient consultation fee', 15000
);

INSERT INTO HOSPITAL.BILL_ITEM (
    BILL_ITEM_ID, BILL_ID, ITEM_NAME, ITEM_AMOUNT
) VALUES (
    910002, 910002, 'Imaging exam fee', 30000
);

INSERT INTO HOSPITAL.PAYMENT (
    PAYMENT_ID, CREATED_AT, BILL_ID, PAYMENT_AMOUNT, PAYMENT_STATUS, PAYMENT_METHOD,
    PAID_AT, PAYMENT_KEY, ORDER_ID, CREATED_BY, CANCELED_BY
) VALUES (
    910001, SYSTIMESTAMP, 910002, 10000, 'COMPLETED', 'CARD',
    SYSTIMESTAMP, 'PAY-DEMO-001', 'ORDER-DEMO-001', 'demo-seed', NULL
);

COMMIT;
