-- =============================================================================
-- Oracle HOSPITAL 스키마 DDL (전체본) - 테이블명 CLINICAL_ 접두사
-- =============================================================================
-- 사용: HOSPITAL 사용자로 접속 후 위에서부터 순서대로 실행.
-- 참고: 스키마 공용이므로 DROP 없음. 최초 1회 생성용.
--
-- Entity → 테이블
--   Visit → CLINICAL_VISIT, VisitStatusHistory → CLINICAL_VISIT_STATUS_HISTORY,
--   VisitQueue → CLINICAL_VISIT_QUEUE, Note → NOTE,
--   Diagnosis → CLINICAL_DIAGNOSIS,
--   Order → CLINICAL_ORDER,
--   OrderItem → CLINICAL_ORDER_ITEM, OrderResult → CLINICAL_ORDER_RESULT,
--   History → CLINICAL_HISTORY (환자별 PHx 구조화: 질병/수술/알러지/복용약)
--   PATIENT_PAST_HISTORY 는 별도 레거시/요약용이면 유지
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. 시퀀스
-- -----------------------------------------------------------------------------
CREATE SEQUENCE CL_VISIT_SEQ
  START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE CL_VISIT_STATUS_HIST_SEQ
  START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE CL_VISIT_QUEUE_SEQ
  START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE CL_NOTE_SEQ
  START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE CL_DIAGNOSIS_SEQ
  START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE CL_ORDER_SEQ
  START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE CL_ORDER_ITEM_SEQ
  START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE CL_ORDER_RESULT_SEQ
  START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE CLINICAL_HISTORY_SEQ
  START WITH 1 INCREMENT BY 1;


-- -----------------------------------------------------------------------------
-- 2. 테이블
-- (신규 환경: 위 시퀀스까지 생성 후, 아래 테이블을 순서대로 실행)
-- -----------------------------------------------------------------------------
-- 참조: CLINICAL_VISIT
--       ├── CLINICAL_VISIT_STATUS_HISTORY, CLINICAL_VISIT_QUEUE,
--       │   NOTE, CLINICAL_ORDER
--       │   NOTE ─── CLINICAL_DIAGNOSIS
--       │   CLINICAL_ORDER ┴── CLINICAL_ORDER_ITEM ── CLINICAL_ORDER_RESULT
-- -----------------------------------------------------------------------------

-- 2.1 CLINICAL_VISIT
CREATE TABLE CLINICAL_VISIT (
  VISIT_ID     NUMBER(19)   NOT NULL,
  PATIENT_ID   NUMBER(19),
  DOCTOR_ID    NUMBER(19),
  RECEPTION_ID NUMBER(19),
  VISIT_STATUS VARCHAR2(20),
  START_TIME   TIMESTAMP,
  END_TIME     TIMESTAMP,
  CREATED_AT   TIMESTAMP,
  UPDATED_AT   TIMESTAMP,
  CONSTRAINT PK_CLN_VISIT PRIMARY KEY (VISIT_ID)
);

-- 2.2 CLINICAL_VISIT_STATUS_HISTORY (FK: CLINICAL_VISIT)
CREATE TABLE CLINICAL_VISIT_STATUS_HISTORY (
  HISTORY_ID   NUMBER(19)   NOT NULL,
  VISIT_ID     NUMBER(19)   NOT NULL,
  STATUS       VARCHAR2(20),
  CHANGED_AT   TIMESTAMP,
  CONSTRAINT PK_CLN_VISIT_STATUS_HIST PRIMARY KEY (HISTORY_ID),
  CONSTRAINT FK_VSH_CLN_VISIT FOREIGN KEY (VISIT_ID) REFERENCES CLINICAL_VISIT (VISIT_ID)
);

-- 2.3 CLINICAL_VISIT_QUEUE (FK: CLINICAL_VISIT)
CREATE TABLE CLINICAL_VISIT_QUEUE (
  QUEUE_ID    NUMBER(19)   NOT NULL,
  VISIT_ID    NUMBER(19)   NOT NULL,
  QUEUE_ORDER NUMBER(10),
  ROOM_ID     NUMBER(19),
  CREATED_AT  TIMESTAMP,
  CONSTRAINT PK_CLN_VISIT_QUEUE PRIMARY KEY (QUEUE_ID),
  CONSTRAINT FK_VQ_CLN_VISIT FOREIGN KEY (VISIT_ID) REFERENCES CLINICAL_VISIT (VISIT_ID)
);

-- 2.4 NOTE (FK: CLINICAL_VISIT)
CREATE TABLE NOTE (
  NOTE_ID         NUMBER(19)    NOT NULL,
  VISIT_ID        NUMBER(19)   NOT NULL,
  CHIEF_COMPLAINT VARCHAR2(2000),
  PRESENT_ILLNESS VARCHAR2(4000),
  MEMO            VARCHAR2(2000),
  STATUS          VARCHAR2(20),
  CREATED_AT      TIMESTAMP,
  UPDATED_AT      TIMESTAMP,
  CONSTRAINT PK_NOTE PRIMARY KEY (NOTE_ID),
  CONSTRAINT FK_NOTE_VISIT FOREIGN KEY (VISIT_ID) REFERENCES CLINICAL_VISIT (VISIT_ID)
);

-- 2.5 CLINICAL_ORDER (FK: CLINICAL_VISIT)
CREATE TABLE CLINICAL_ORDER (
  ORDER_ID     NUMBER(19)   NOT NULL,
  VISIT_ID     NUMBER(19)   NOT NULL,
  ORDER_TYPE   VARCHAR2(20),
  ORDER_STATUS VARCHAR2(20),
  DOCTOR_ID    NUMBER(19),
  ORDER_DATE   TIMESTAMP,
  CREATED_AT   TIMESTAMP,
  UPDATED_AT   TIMESTAMP,
  CONSTRAINT PK_CLN_ORDER PRIMARY KEY (ORDER_ID),
  CONSTRAINT FK_CO_CLN_VISIT FOREIGN KEY (VISIT_ID) REFERENCES CLINICAL_VISIT (VISIT_ID)
);

-- 2.6 CLINICAL_DIAGNOSIS (FK: NOTE)
CREATE TABLE CLINICAL_DIAGNOSIS (
  DIAGNOSIS_ID   NUMBER(19)     NOT NULL,
  NOTE_ID        NUMBER(19)   NOT NULL,
  PATIENT_CODE   VARCHAR2(50),
  DIAGNOSIS_CODE VARCHAR2(50),
  DESCRIPTION    VARCHAR2(1000),
  CREATED_AT     TIMESTAMP,
  CONSTRAINT PK_CLN_DIAGNOSIS PRIMARY KEY (DIAGNOSIS_ID),
  CONSTRAINT FK_CD_NOTE FOREIGN KEY (NOTE_ID) REFERENCES NOTE (NOTE_ID)
);

-- 2.7 CLINICAL_ORDER_ITEM (FK: CLINICAL_ORDER)
CREATE TABLE CLINICAL_ORDER_ITEM (
  ORDER_ITEM_ID NUMBER(19)    NOT NULL,
  ORDER_ID      NUMBER(19)   NOT NULL,
  ITEM_CODE     VARCHAR2(50),
  DOSE          NUMBER(10,2),
  FREQUENCY     VARCHAR2(100),
  DURATION      VARCHAR2(100),
  CREATED_AT    TIMESTAMP,
  CONSTRAINT PK_CLN_ORDER_ITEM PRIMARY KEY (ORDER_ITEM_ID),
  CONSTRAINT FK_COI_CLN_ORDER FOREIGN KEY (ORDER_ID) REFERENCES CLINICAL_ORDER (ORDER_ID)
);

-- 2.8 CLINICAL_ORDER_RESULT (FK: CLINICAL_ORDER_ITEM)
CREATE TABLE CLINICAL_ORDER_RESULT (
  RESULT_ID      NUMBER(19)    NOT NULL,
  ORDER_ITEM_ID  NUMBER(19)   NOT NULL,
  RESULT_VALUE   VARCHAR2(2000),
  RESULT_STATUS  VARCHAR2(20),
  RESULT_DATE    TIMESTAMP,
  CREATED_AT     TIMESTAMP,
  CONSTRAINT PK_CLN_ORDER_RESULT PRIMARY KEY (RESULT_ID),
  CONSTRAINT FK_COR_CLN_ORDER_ITEM FOREIGN KEY (ORDER_ITEM_ID) REFERENCES CLINICAL_ORDER_ITEM (ORDER_ITEM_ID)
);

-- 2.9 CLINICAL_HISTORY (History 엔티티 - PHx 구조화 과거력, 환자 단위)
CREATE TABLE CLINICAL_HISTORY (
  ID             NUMBER(19)    NOT NULL,
  PATIENT_ID     NUMBER(19)    NOT NULL,
  HISTORY_TYPE   VARCHAR2(20)  NOT NULL,
  NAME           VARCHAR2(100) NOT NULL,
  MEMO           VARCHAR2(500),
  CREATED_AT     TIMESTAMP,
  UPDATED_AT     TIMESTAMP,
  CONSTRAINT PK_CLINICAL_HISTORY PRIMARY KEY (ID)
);

-- 2.10 PATIENT_PAST_HISTORY (레거시/요약 과거력, History 엔티티와 별도)
CREATE TABLE PATIENT_PAST_HISTORY (
  PATIENT_ID  NUMBER(19)   NOT NULL,
  DISEASES    VARCHAR2(4000),
  SURGERIES   VARCHAR2(4000),
  ALLERGIES   VARCHAR2(4000),
  MEDICATIONS VARCHAR2(4000),
  CREATED_AT  TIMESTAMP,
  UPDATED_AT  TIMESTAMP,
  CONSTRAINT PK_PATIENT_PAST_HIST PRIMARY KEY (PATIENT_ID)
);

CREATE SEQUENCE CLINICAL_VITAL_SAVE_AUDIT_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE CLINICAL_VITAL_SAVE_AUDIT (
  SAVE_AUDIT_ID NUMBER(19)   NOT NULL,
  VISIT_ID      NUMBER(19)   NOT NULL,
  RECORDED_AT   TIMESTAMP,
  SAVED_AT      TIMESTAMP    NOT NULL,
  CHANGE_SUMMARY VARCHAR2(4000),
  CONSTRAINT PK_CLINICAL_VITAL_SAVE_AUDIT PRIMARY KEY (SAVE_AUDIT_ID),
  CONSTRAINT FK_CVSA_CLN_VISIT FOREIGN KEY (VISIT_ID) REFERENCES CLINICAL_VISIT (VISIT_ID)
);
