SELECT COUNT(*) FROM CLINICAL_VISIT WHERE VISIT_ID = 1;

INSERT INTO CLINICAL_VISIT (VISIT_ID, PATIENT_ID, DOCTOR_ID, RECEPTION_ID, VISIT_STATUS, START_TIME, CREATED_AT, UPDATED_AT)
SELECT 1, 1, 1, 1, 'WAITING', SYSTIMESTAMP, SYSTIMESTAMP, SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CLINICAL_VISIT WHERE VISIT_ID = 1);

INSERT INTO CLINICAL_VISIT (VISIT_ID, PATIENT_ID, DOCTOR_ID, RECEPTION_ID, VISIT_STATUS, START_TIME, CREATED_AT, UPDATED_AT)
SELECT 2, 2, 1, 1, 'IN_PROGRESS', SYSTIMESTAMP, SYSTIMESTAMP, SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CLINICAL_VISIT WHERE VISIT_ID = 2);

INSERT INTO CLINICAL_VISIT (VISIT_ID, PATIENT_ID, DOCTOR_ID, RECEPTION_ID, VISIT_STATUS, START_TIME, END_TIME, CREATED_AT, UPDATED_AT)
SELECT 3, 1, 1, 1, 'COMPLETED', SYSTIMESTAMP - 1, SYSTIMESTAMP, SYSTIMESTAMP, SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CLINICAL_VISIT WHERE VISIT_ID = 3);

INSERT INTO NOTE (NOTE_ID, VISIT_ID, CHIEF_COMPLAINT, STATUS, CREATED_AT, UPDATED_AT)
SELECT CL_NOTE_SEQ.NEXTVAL, 1, '두통', 'DRAFT', SYSTIMESTAMP, SYSTIMESTAMP FROM DUAL
WHERE EXISTS (SELECT 1 FROM CLINICAL_VISIT WHERE VISIT_ID = 1)
  AND NOT EXISTS (SELECT 1 FROM NOTE WHERE VISIT_ID = 1);

INSERT INTO CLINICAL_ORDER (ORDER_ID, VISIT_ID, ORDER_TYPE, ORDER_STATUS, DOCTOR_ID, ORDER_DATE, CREATED_AT, UPDATED_AT)
SELECT CL_ORDER_SEQ.NEXTVAL, 1, 'LAB', 'REQUESTED', 1, SYSTIMESTAMP, SYSTIMESTAMP, SYSTIMESTAMP FROM DUAL
WHERE EXISTS (SELECT 1 FROM CLINICAL_VISIT WHERE VISIT_ID = 1);

COMMIT;
EXIT;
