MERGE INTO CMH.POSITIONS t
USING (
    SELECT 1 AS id, 'ADMIN' AS domain, '관리자' AS title FROM dual
    UNION ALL SELECT 2, 'DOCTOR', '의사' FROM dual
    UNION ALL SELECT 3, 'NURSE', '간호사' FROM dual
    UNION ALL SELECT 4, 'RECEPTION', '원무' FROM dual
    UNION ALL SELECT 5, 'RADIOLOGY_TECH', '방사선사' FROM dual
    UNION ALL SELECT 6, 'CLINICAL_LAB_TECH', '임상병리사' FROM dual
    UNION ALL SELECT 7, 'PATHOLOGY_COORDINATOR', '병리 담당자' FROM dual
    UNION ALL SELECT 8, 'ENDOSCOPY_COORDINATOR', '내시경 담당자' FROM dual
    UNION ALL SELECT 9, 'PHYSIOLOGY_TEST_COORDINATOR', '생리기능검사 담당자' FROM dual
) s
ON (t.ID = s.id)
WHEN MATCHED THEN
  UPDATE SET
    t.DOMAIN = s.domain,
    t.TITLE = s.title,
    t.IS_ACTIVE = 'Y',
    t.SORT_ORDER = s.id,
    t.UPDATED_AT = SYSDATE
WHEN NOT MATCHED THEN
  INSERT (ID, DOMAIN, TITLE, IS_ACTIVE, SORT_ORDER, CREATED_AT, UPDATED_AT)
  VALUES (s.id, s.domain, s.title, 'Y', s.id, SYSDATE, SYSDATE);

UPDATE CMH.STAFF
SET STATUS = 'ACTIVE',
    STATUS_CODE = 'ACTIVE',
    DOMAIN_ROLE = 'NURSE',
    POSITION_ID = 3,
    UPDATED_AT = SYSDATE
WHERE USERNAME = 'dark';

UPDATE CMH.STAFF
SET STATUS = 'ACTIVE',
    STATUS_CODE = 'ACTIVE',
    DOMAIN_ROLE = 'RADIOLOGY_TECH',
    POSITION_ID = 5,
    UPDATED_AT = SYSDATE
WHERE USERNAME = 'blaster';

UPDATE CMH.STAFF
SET STATUS = 'ACTIVE',
    STATUS_CODE = 'ACTIVE',
    DOMAIN_ROLE = 'CLINICAL_LAB_TECH',
    POSITION_ID = 6,
    UPDATED_AT = SYSDATE
WHERE USERNAME = 'zero';

UPDATE CMH.STAFF
SET STATUS = 'ACTIVE',
    STATUS_CODE = 'ACTIVE',
    DOMAIN_ROLE = 'PATHOLOGY_COORDINATOR',
    POSITION_ID = 7,
    UPDATED_AT = SYSDATE
WHERE USERNAME = 'demonavenger';

UPDATE CMH.STAFF
SET STATUS = 'ACTIVE',
    STATUS_CODE = 'ACTIVE',
    DOMAIN_ROLE = 'ENDOSCOPY_COORDINATOR',
    POSITION_ID = 8,
    UPDATED_AT = SYSDATE
WHERE USERNAME = 'len';

UPDATE CMH.STAFF
SET STATUS = 'ACTIVE',
    STATUS_CODE = 'ACTIVE',
    DOMAIN_ROLE = 'PHYSIOLOGY_TEST_COORDINATOR',
    POSITION_ID = 9,
    UPDATED_AT = SYSDATE
WHERE USERNAME = 'adel';

UPDATE CMH.STAFF
SET STATUS = 'ACTIVE',
    STATUS_CODE = 'ACTIVE',
    DOMAIN_ROLE = 'DOCTOR',
    POSITION_ID = 2,
    UPDATED_AT = SYSDATE
WHERE USERNAME = 'soulmaster';

UPDATE CMH.STAFF
SET STATUS = 'ACTIVE',
    STATUS_CODE = 'ACTIVE',
    DOMAIN_ROLE = 'ADMIN',
    POSITION_ID = 1,
    UPDATED_AT = SYSDATE
WHERE USERNAME = 'kaiser';

COMMIT;
