DECLARE
  PROCEDURE exec_ddl(p_sql IN CLOB) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -955 THEN
        NULL;
      ELSE
        RAISE;
      END IF;
  END;
BEGIN
  exec_ddl('CREATE TABLE CMH.HANDOVER_OPTION (
      ID NUMBER NOT NULL,
      OPTION_TYPE VARCHAR2(30) NOT NULL,
      LABEL VARCHAR2(100) NOT NULL,
      SORT_ORDER NUMBER NOT NULL,
      IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_HANDOVER_OPTION PRIMARY KEY (ID)
  )');

  exec_ddl('CREATE SEQUENCE CMH.HANDOVER_OPTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE');

  exec_ddl('CREATE UNIQUE INDEX CMH.UX_HANDOVER_OPTION_TYPE_LABEL ON CMH.HANDOVER_OPTION(OPTION_TYPE, LABEL)');
END;
/

MERGE INTO CMH.HANDOVER_OPTION t
USING (
  SELECT 'COMPLETED' AS option_type, '투약 완료' AS label, 1 AS sort_order FROM dual UNION ALL
  SELECT 'COMPLETED', '처치 완료', 2 FROM dual UNION ALL
  SELECT 'COMPLETED', '검사 시행', 3 FROM dual UNION ALL
  SELECT 'COMPLETED', '회진 보고', 4 FROM dual UNION ALL
  SELECT 'COMPLETED', '보호자 설명', 5 FROM dual UNION ALL
  SELECT 'COMPLETED', '의사 호출 완료', 6 FROM dual UNION ALL
  SELECT 'COMPLETED', '기타(직접입력)', 999 FROM dual UNION ALL
  SELECT 'TODO', '바이탈 재측정', 1 FROM dual UNION ALL
  SELECT 'TODO', '검사결과 확인', 2 FROM dual UNION ALL
  SELECT 'TODO', '투약 예정', 3 FROM dual UNION ALL
  SELECT 'TODO', '드레싱/처치 예정', 4 FROM dual UNION ALL
  SELECT 'TODO', '의사 보고 필요', 5 FROM dual UNION ALL
  SELECT 'TODO', '보호자 안내 예정', 6 FROM dual UNION ALL
  SELECT 'TODO', '기타(직접입력)', 999 FROM dual
) s
ON (t.OPTION_TYPE = s.option_type AND t.LABEL = s.label)
WHEN MATCHED THEN
  UPDATE SET t.SORT_ORDER = s.sort_order, t.IS_ACTIVE = 1
WHEN NOT MATCHED THEN
  INSERT (ID, OPTION_TYPE, LABEL, SORT_ORDER, IS_ACTIVE)
  VALUES (CMH.HANDOVER_OPTION_SEQ.NEXTVAL, s.option_type, s.label, s.sort_order, 1);

COMMIT;
