DECLARE
  PROCEDURE exec_ddl(p_sql IN CLOB) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE IN (-955, -1430) THEN NULL; ELSE RAISE; END IF;
  END;
BEGIN
  exec_ddl('CREATE TABLE CMH.TRAINING_SESSION (
    ID NUMBER PRIMARY KEY,
    TRAINING_DATE DATE NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CATEGORY VARCHAR2(20) NOT NULL,
    DEPARTMENT_NAME VARCHAR2(100) NOT NULL,
    CAPACITY NUMBER NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
  )');

  exec_ddl('CREATE SEQUENCE CMH.TRAINING_SESSION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE');

  exec_ddl('CREATE TABLE CMH.TRAINING_ENROLLMENT (
    ID NUMBER PRIMARY KEY,
    SESSION_ID NUMBER NOT NULL,
    STAFF_ID VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    PROCESS_REASON VARCHAR2(500),
    PROCESSED_BY VARCHAR2(100),
    PROCESSED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_TRAINING_ENROLL_SESSION FOREIGN KEY (SESSION_ID) REFERENCES CMH.TRAINING_SESSION(ID)
  )');

  exec_ddl('ALTER TABLE CMH.TRAINING_ENROLLMENT ADD PROCESS_REASON VARCHAR2(500)');
  exec_ddl('ALTER TABLE CMH.TRAINING_ENROLLMENT ADD PROCESSED_BY VARCHAR2(100)');
  exec_ddl('ALTER TABLE CMH.TRAINING_ENROLLMENT ADD PROCESSED_AT TIMESTAMP');

  exec_ddl('CREATE SEQUENCE CMH.TRAINING_ENROLLMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE');
  exec_ddl('CREATE UNIQUE INDEX CMH.UX_TRAINING_ENROLL_UNIQ ON CMH.TRAINING_ENROLLMENT(SESSION_ID, STAFF_ID)');
END;
/

MERGE INTO CMH.TRAINING_SESSION t
USING (
  SELECT 1 AS id, DATE '2026-02-24' AS training_date, '감염관리 기본교육' AS title, '필수' AS category, '전체' AS department_name, 40 AS capacity FROM dual UNION ALL
  SELECT 2, DATE '2026-02-25', '개인정보보호 실무', '필수', '전체', 30 FROM dual UNION ALL
  SELECT 3, DATE '2026-02-27', '응급상황 대응 시뮬레이션', '선택', '간호부', 24 FROM dual UNION ALL
  SELECT 4, DATE '2026-03-03', '환자경험 개선 워크숍', '선택', '원무/행정', 20 FROM dual UNION ALL
  SELECT 101, DATE '2026-03-10', '환자안전 심화 교육', '필수', '전체', 40 FROM dual UNION ALL
  SELECT 102, DATE '2026-03-14', '응급대응 실습 워크숍', '선택', '간호부', 30 FROM dual UNION ALL
  SELECT 103, DATE '2026-03-20', '개인정보보호 재이수 과정', '필수', '전체', 35 FROM dual UNION ALL
  SELECT 104, DATE '2026-03-25', '의료정보 시스템 보안 교육', '선택', '원무/행정', 25 FROM dual
) s
ON (t.ID = s.id)
WHEN MATCHED THEN UPDATE SET t.TRAINING_DATE=s.training_date, t.TITLE=s.title, t.CATEGORY=s.category, t.DEPARTMENT_NAME=s.department_name, t.CAPACITY=s.capacity, t.IS_ACTIVE=1
WHEN NOT MATCHED THEN INSERT (ID, TRAINING_DATE, TITLE, CATEGORY, DEPARTMENT_NAME, CAPACITY, IS_ACTIVE) VALUES (s.id, s.training_date, s.title, s.category, s.department_name, s.capacity, 1);

MERGE INTO CMH.TRAINING_ENROLLMENT e
USING (
  SELECT 1 AS session_id, 'nursepmj' AS staff_id, 'COMPLETED' AS status FROM dual UNION ALL
  SELECT 1, 'nurseosb', 'COMPLETED' FROM dual UNION ALL
  SELECT 2, 'drkimtw', 'COMPLETED' FROM dual UNION ALL
  SELECT 2, 'admin', 'COMPLETED' FROM dual UNION ALL
  SELECT 3, 'nursepmj', 'APPLIED' FROM dual UNION ALL
  SELECT 101, 'admin', 'COMPLETED' FROM dual UNION ALL
  SELECT 102, 'admin', 'COMPLETED' FROM dual UNION ALL
  SELECT 103, 'admin', 'COMPLETED' FROM dual UNION ALL
  SELECT 104, 'admin', 'COMPLETED' FROM dual UNION ALL
  SELECT 101, 'nursepmj', 'COMPLETED' FROM dual UNION ALL
  SELECT 102, 'nurseosb', 'COMPLETED' FROM dual UNION ALL
  SELECT 101, 'babo99con', 'COMPLETED' FROM dual
) s
ON (e.SESSION_ID = s.session_id AND e.STAFF_ID = s.staff_id)
WHEN MATCHED THEN UPDATE SET e.STATUS=s.status, e.UPDATED_AT=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (ID, SESSION_ID, STAFF_ID, STATUS, CREATED_AT, UPDATED_AT) VALUES (CMH.TRAINING_ENROLLMENT_SEQ.NEXTVAL, s.session_id, s.staff_id, s.status, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CMH.TRAINING_ENROLLMENT e
USING (
  SELECT t.ID AS session_id,
         TRIM(s.USERNAME) AS staff_id,
         'COMPLETED' AS status
  FROM CMH.TRAINING_SESSION t
  CROSS JOIN CMH.STAFF s
  WHERE t.ID IN (101, 102, 103, 104)
    AND TRIM(s.USERNAME) IS NOT NULL
) x
ON (e.SESSION_ID = x.session_id AND e.STAFF_ID = x.staff_id)
WHEN MATCHED THEN
  UPDATE SET e.STATUS = x.status, e.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN
  INSERT (ID, SESSION_ID, STAFF_ID, STATUS, CREATED_AT, UPDATED_AT)
  VALUES (CMH.TRAINING_ENROLLMENT_SEQ.NEXTVAL, x.session_id, x.staff_id, x.status, SYSTIMESTAMP, SYSTIMESTAMP);

COMMIT;
