DECLARE
    PROCEDURE exec_ddl(p_sql IN CLOB) IS
    BEGIN
        EXECUTE IMMEDIATE p_sql;
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -955 THEN
                NULL;
            ELSE
                RAISE;
            END IF;
    END;
BEGIN
    exec_ddl('CREATE TABLE CMH.PATIENT (
        PATIENT_ID NUMBER NOT NULL,
        PATIENT_NO VARCHAR2(20),
        NAME VARCHAR2(50) NOT NULL,
        GENDER VARCHAR2(1),
        BIRTH_DATE DATE,
        PHONE VARCHAR2(20),
        EMAIL VARCHAR2(100),
        ADDRESS VARCHAR2(200),
        ADDRESS_DETAIL VARCHAR2(100),
        GUARDIAN_NAME VARCHAR2(50),
        GUARDIAN_PHONE VARCHAR2(20),
        GUARDIAN_RELATION VARCHAR2(30),
        IS_FOREIGNER NUMBER(1) NOT NULL,
        CONTACT_PRIORITY VARCHAR2(20) NOT NULL,
        NOTE VARCHAR2(500),
        STATUS_CODE VARCHAR2(20) NOT NULL,
        IS_VIP NUMBER(1) NOT NULL,
        PHOTO_URL VARCHAR2(500),
        CREATED_AT DATE,
        UPDATED_AT DATE
    )');

    exec_ddl('CREATE SEQUENCE CMH.PATIENT_ID_SEQ START WITH 1 INCREMENT BY 1');

    exec_ddl('CREATE TABLE CMH.PATIENT_MEMO (
        MEMO_ID NUMBER NOT NULL,
        PATIENT_ID NUMBER NOT NULL,
        MEMO CLOB NOT NULL,
        CREATED_BY VARCHAR2(100),
        CREATED_AT DATE,
        UPDATED_AT DATE
    )');

    exec_ddl('CREATE SEQUENCE CMH.PATIENT_MEMO_SEQ START WITH 1 INCREMENT BY 1');

    exec_ddl('CREATE TABLE CMH.PATIENT_FLAG (
        FLAG_ID NUMBER NOT NULL,
        PATIENT_ID NUMBER NOT NULL,
        FLAG_TYPE VARCHAR2(20) NOT NULL,
        NOTE VARCHAR2(500),
        ACTIVE_YN NUMBER(1) NOT NULL,
        CREATED_BY VARCHAR2(100),
        CREATED_AT DATE,
        UPDATED_AT DATE
    )');

    exec_ddl('CREATE SEQUENCE CMH.PATIENT_FLAG_SEQ START WITH 1 INCREMENT BY 1');

    COMMIT;
END;
/
