-- Ensure CMH.AUTH_USER_ID_SEQ is ahead of existing CMH.AUTH_USER IDs
DECLARE
  v_target NUMBER;
  v_next   NUMBER;
  v_inc    NUMBER;
BEGIN
  SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(ID, '[0-9]{4}$'))), 0) + 1
    INTO v_target
    FROM CMH.AUTH_USER;

  EXECUTE IMMEDIATE 'SELECT CMH.AUTH_USER_ID_SEQ.NEXTVAL FROM DUAL' INTO v_next;

  IF v_next < v_target THEN
    v_inc := v_target - v_next;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE CMH.AUTH_USER_ID_SEQ INCREMENT BY ' || v_inc;
    EXECUTE IMMEDIATE 'SELECT CMH.AUTH_USER_ID_SEQ.NEXTVAL FROM DUAL' INTO v_next;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE CMH.AUTH_USER_ID_SEQ INCREMENT BY 1';
  END IF;
END;
/
