DECLARE
  FUNCTION table_exists(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN NUMBER IS
    v_cnt NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_cnt
      FROM ALL_TABLES
     WHERE OWNER = UPPER(p_owner)
       AND TABLE_NAME = UPPER(p_table);
    RETURN v_cnt;
  END;

  FUNCTION sequence_exists(p_owner IN VARCHAR2, p_seq IN VARCHAR2) RETURN NUMBER IS
    v_cnt NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_cnt
      FROM ALL_SEQUENCES
     WHERE SEQUENCE_OWNER = UPPER(p_owner)
       AND SEQUENCE_NAME = UPPER(p_seq);
    RETURN v_cnt;
  END;

  FUNCTION constraint_exists(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN NUMBER IS
    v_cnt NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_cnt
      FROM ALL_CONSTRAINTS
     WHERE OWNER = UPPER(p_owner)
       AND CONSTRAINT_NAME = UPPER(p_name);
    RETURN v_cnt;
  END;

  FUNCTION index_exists(p_owner IN VARCHAR2, p_name IN VARCHAR2) RETURN NUMBER IS
    v_cnt NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_cnt
      FROM ALL_INDEXES
     WHERE OWNER = UPPER(p_owner)
       AND INDEX_NAME = UPPER(p_name);
    RETURN v_cnt;
  END;

  PROCEDURE exec_ddl(p_sql IN CLOB) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  END;

  v_menu_rows NUMBER;
BEGIN
  IF table_exists('CMH', 'MENU') = 0 THEN
    exec_ddl('CREATE TABLE CMH.MENU (
      ID NUMBER NOT NULL,
      PARENT_ID NUMBER,
      CODE VARCHAR2(50) NOT NULL,
      NAME VARCHAR2(100) NOT NULL,
      PATH VARCHAR2(200),
      ICON VARCHAR2(50),
      SORT_ORDER NUMBER NOT NULL,
      IS_ACTIVE NUMBER(1) NOT NULL,
      CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
    )');
  END IF;

  IF constraint_exists('CMH', 'PK_CMH_MENU') = 0 THEN
    BEGIN
      exec_ddl('ALTER TABLE CMH.MENU ADD CONSTRAINT PK_CMH_MENU PRIMARY KEY (ID)');
    EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -2260 THEN RAISE; END IF;
    END;
  END IF;

  IF index_exists('CMH', 'UX_CMH_MENU_CODE') = 0 THEN
    BEGIN
      exec_ddl('CREATE UNIQUE INDEX CMH.UX_CMH_MENU_CODE ON CMH.MENU(CODE)');
    EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -955 THEN RAISE; END IF;
    END;
  END IF;

  SELECT COUNT(*) INTO v_menu_rows FROM CMH.MENU;
  IF v_menu_rows = 0 AND table_exists('LHS', 'MENU') > 0 THEN
    BEGIN
      INSERT INTO CMH.MENU (ID, PARENT_ID, CODE, NAME, PATH, ICON, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
      SELECT ID, PARENT_ID, CODE, NAME, PATH, ICON, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT
        FROM LHS.MENU;
    EXCEPTION WHEN OTHERS THEN
      NULL;
    END;
  END IF;

  IF table_exists('CMH', 'LEAVE_REQUEST') = 0 THEN
    exec_ddl('CREATE TABLE CMH.LEAVE_REQUEST (
      ID NUMBER(19) PRIMARY KEY,
      REQUESTER_ID VARCHAR2(100) NOT NULL,
      REQUESTER_NAME VARCHAR2(100) NOT NULL,
      DEPARTMENT_NAME VARCHAR2(100),
      LEAVE_TYPE VARCHAR2(30) NOT NULL,
      FROM_DATE VARCHAR2(20) NOT NULL,
      TO_DATE VARCHAR2(20) NOT NULL,
      REASON VARCHAR2(2000),
      FINAL_STATUS VARCHAR2(20) DEFAULT ''PENDING'' NOT NULL,
      CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
      UPDATED_AT DATE DEFAULT SYSDATE NOT NULL
    )');
  END IF;

  IF table_exists('CMH', 'LEAVE_APPROVAL_LINE') = 0 THEN
    exec_ddl('CREATE TABLE CMH.LEAVE_APPROVAL_LINE (
      ID NUMBER(19) PRIMARY KEY,
      REQUEST_ID NUMBER(19) NOT NULL,
      LINE_TYPE VARCHAR2(20) NOT NULL,
      APPROVER_ID VARCHAR2(100) NOT NULL,
      APPROVER_NAME VARCHAR2(100) NOT NULL,
      LINE_ORDER NUMBER(5) DEFAULT 1 NOT NULL,
      ACTION_STATUS VARCHAR2(20) DEFAULT ''PENDING'' NOT NULL,
      ACTED_AT VARCHAR2(20),
      CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
      UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
      CONSTRAINT FK_LEAVE_LINE_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES CMH.LEAVE_REQUEST(ID)
    )');
  END IF;

  IF table_exists('CMH', 'SHIFT_ASSIGNMENT') = 0 THEN
    exec_ddl('CREATE TABLE CMH.SHIFT_ASSIGNMENT (
      ID NUMBER(19) PRIMARY KEY,
      SHIFT_DATE VARCHAR2(20) NOT NULL,
      STAFF_ID VARCHAR2(100) NOT NULL,
      STAFF_NAME VARCHAR2(100) NOT NULL,
      DEPARTMENT_NAME VARCHAR2(100),
      SHIFT_TYPE VARCHAR2(20) NOT NULL,
      CREATED_BY VARCHAR2(100) NOT NULL,
      CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
      UPDATED_AT DATE DEFAULT SYSDATE NOT NULL
    )');
  END IF;

  IF sequence_exists('CMH', 'LEAVE_REQUEST_SEQ') = 0 THEN
    exec_ddl('CREATE SEQUENCE CMH.LEAVE_REQUEST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE');
  END IF;

  IF sequence_exists('CMH', 'LEAVE_APPROVAL_LINE_SEQ') = 0 THEN
    exec_ddl('CREATE SEQUENCE CMH.LEAVE_APPROVAL_LINE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE');
  END IF;

  IF sequence_exists('CMH', 'SHIFT_ASSIGNMENT_SEQ') = 0 THEN
    exec_ddl('CREATE SEQUENCE CMH.SHIFT_ASSIGNMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE');
  END IF;

  IF index_exists('CMH', 'UX_SHIFT_DATE_STAFF_TYPE') = 0 THEN
    exec_ddl('CREATE UNIQUE INDEX CMH.UX_SHIFT_DATE_STAFF_TYPE ON CMH.SHIFT_ASSIGNMENT (SHIFT_DATE, STAFF_ID, SHIFT_TYPE)');
  END IF;

  IF index_exists('CMH', 'IDX_LEAVE_REQ_REQUESTER') = 0 THEN
    exec_ddl('CREATE INDEX CMH.IDX_LEAVE_REQ_REQUESTER ON CMH.LEAVE_REQUEST (REQUESTER_ID, CREATED_AT)');
  END IF;

  IF index_exists('CMH', 'IDX_LEAVE_REQ_STATUS') = 0 THEN
    exec_ddl('CREATE INDEX CMH.IDX_LEAVE_REQ_STATUS ON CMH.LEAVE_REQUEST (FINAL_STATUS, FROM_DATE, TO_DATE)');
  END IF;

  IF index_exists('CMH', 'IDX_LEAVE_LINE_APPROVER') = 0 THEN
    exec_ddl('CREATE INDEX CMH.IDX_LEAVE_LINE_APPROVER ON CMH.LEAVE_APPROVAL_LINE (APPROVER_ID, ACTION_STATUS, LINE_TYPE)');
  END IF;

  IF index_exists('CMH', 'IDX_LEAVE_LINE_REQ') = 0 THEN
    exec_ddl('CREATE INDEX CMH.IDX_LEAVE_LINE_REQ ON CMH.LEAVE_APPROVAL_LINE (REQUEST_ID, LINE_ORDER)');
  END IF;

  IF index_exists('CMH', 'IDX_SHIFT_DATE') = 0 THEN
    exec_ddl('CREATE INDEX CMH.IDX_SHIFT_DATE ON CMH.SHIFT_ASSIGNMENT (SHIFT_DATE, SHIFT_TYPE)');
  END IF;

  IF table_exists('CMH', 'HANDOVER_OPTION') = 0 THEN
    exec_ddl('CREATE TABLE CMH.HANDOVER_OPTION (
      ID NUMBER NOT NULL,
      OPTION_TYPE VARCHAR2(30) NOT NULL,
      LABEL VARCHAR2(100) NOT NULL,
      SORT_ORDER NUMBER NOT NULL,
      IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_HANDOVER_OPTION PRIMARY KEY (ID)
    )');
  END IF;

  IF sequence_exists('CMH', 'HANDOVER_OPTION_SEQ') = 0 THEN
    exec_ddl('CREATE SEQUENCE CMH.HANDOVER_OPTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE');
  END IF;

  IF index_exists('CMH', 'UX_HANDOVER_OPTION_TYPE_LABEL') = 0 THEN
    exec_ddl('CREATE UNIQUE INDEX CMH.UX_HANDOVER_OPTION_TYPE_LABEL ON CMH.HANDOVER_OPTION(OPTION_TYPE, LABEL)');
  END IF;

  IF table_exists('CMH', 'TRAINING_SESSION') = 0 THEN
    exec_ddl('CREATE TABLE CMH.TRAINING_SESSION (
      ID NUMBER PRIMARY KEY,
      TRAINING_DATE DATE NOT NULL,
      TITLE VARCHAR2(200) NOT NULL,
      CATEGORY VARCHAR2(20) NOT NULL,
      DEPARTMENT_NAME VARCHAR2(100) NOT NULL,
      CAPACITY NUMBER NOT NULL,
      IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
    )');
  END IF;

  IF sequence_exists('CMH', 'TRAINING_SESSION_SEQ') = 0 THEN
    exec_ddl('CREATE SEQUENCE CMH.TRAINING_SESSION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE');
  END IF;

  IF table_exists('CMH', 'TRAINING_ENROLLMENT') = 0 THEN
    exec_ddl('CREATE TABLE CMH.TRAINING_ENROLLMENT (
      ID NUMBER PRIMARY KEY,
      SESSION_ID NUMBER NOT NULL,
      STAFF_ID VARCHAR2(100) NOT NULL,
      STATUS VARCHAR2(20) NOT NULL,
      PROCESS_REASON VARCHAR2(500),
      PROCESSED_BY VARCHAR2(100),
      PROCESSED_AT TIMESTAMP,
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
      CONSTRAINT FK_TRAINING_ENROLL_SESSION FOREIGN KEY (SESSION_ID) REFERENCES CMH.TRAINING_SESSION(ID)
    )');
  END IF;

  IF sequence_exists('CMH', 'TRAINING_ENROLLMENT_SEQ') = 0 THEN
    exec_ddl('CREATE SEQUENCE CMH.TRAINING_ENROLLMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE');
  END IF;

  IF index_exists('CMH', 'UX_TRAINING_ENROLL_UNIQ') = 0 THEN
    exec_ddl('CREATE UNIQUE INDEX CMH.UX_TRAINING_ENROLL_UNIQ ON CMH.TRAINING_ENROLLMENT(SESSION_ID, STAFF_ID)');
  END IF;

  COMMIT;
END;
/
