DECLARE
  FUNCTION table_exists(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN NUMBER IS
    v_cnt NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_cnt
      FROM ALL_TABLES
     WHERE OWNER = UPPER(p_owner)
       AND TABLE_NAME = UPPER(p_table);
    RETURN v_cnt;
  END;

  FUNCTION seq_exists(p_owner IN VARCHAR2, p_seq IN VARCHAR2) RETURN NUMBER IS
    v_cnt NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_cnt
      FROM ALL_SEQUENCES
     WHERE SEQUENCE_OWNER = UPPER(p_owner)
       AND SEQUENCE_NAME = UPPER(p_seq);
    RETURN v_cnt;
  END;

  FUNCTION trigger_exists(p_owner IN VARCHAR2, p_trigger IN VARCHAR2) RETURN NUMBER IS
    v_cnt NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_cnt
      FROM ALL_TRIGGERS
     WHERE OWNER = UPPER(p_owner)
       AND TRIGGER_NAME = UPPER(p_trigger);
    RETURN v_cnt;
  END;

  PROCEDURE exec_ddl(p_sql IN CLOB) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  END;
BEGIN
  IF table_exists('CMH', 'PATIENT') = 0 THEN
    exec_ddl('CREATE TABLE CMH.PATIENT (
      PATIENT_ID NUMBER NOT NULL,
      PATIENT_NO VARCHAR2(20),
      NAME VARCHAR2(50) NOT NULL,
      GENDER VARCHAR2(1),
      BIRTH_DATE DATE,
      PHONE VARCHAR2(20),
      EMAIL VARCHAR2(100),
      ADDRESS VARCHAR2(200),
      ADDRESS_DETAIL VARCHAR2(100),
      GUARDIAN_NAME VARCHAR2(50),
      GUARDIAN_PHONE VARCHAR2(20),
      GUARDIAN_RELATION VARCHAR2(30),
      IS_FOREIGNER NUMBER(1) NOT NULL,
      CONTACT_PRIORITY VARCHAR2(20) NOT NULL,
      NOTE VARCHAR2(500),
      STATUS_CODE VARCHAR2(20) NOT NULL,
      IS_VIP NUMBER(1) NOT NULL,
      PHOTO_URL VARCHAR2(500),
      CREATED_AT DATE,
      UPDATED_AT DATE
    )');
  END IF;

  IF table_exists('CMH', 'PATIENT_MEMO') = 0 THEN
    exec_ddl('CREATE TABLE CMH.PATIENT_MEMO (
      MEMO_ID NUMBER NOT NULL,
      PATIENT_ID NUMBER NOT NULL,
      MEMO CLOB NOT NULL,
      CREATED_BY VARCHAR2(100),
      CREATED_AT DATE,
      UPDATED_AT DATE
    )');
  END IF;

  IF table_exists('CMH', 'PATIENT_FLAG') = 0 THEN
    exec_ddl('CREATE TABLE CMH.PATIENT_FLAG (
      FLAG_ID NUMBER NOT NULL,
      PATIENT_ID NUMBER NOT NULL,
      FLAG_TYPE VARCHAR2(20) NOT NULL,
      NOTE VARCHAR2(500),
      ACTIVE_YN NUMBER(1) NOT NULL,
      CREATED_BY VARCHAR2(100),
      CREATED_AT DATE,
      UPDATED_AT DATE
    )');
  END IF;

  IF table_exists('CMH', 'MENU') = 0 THEN
    exec_ddl('CREATE TABLE CMH.MENU (
      ID NUMBER NOT NULL,
      PARENT_ID NUMBER,
      CODE VARCHAR2(50) NOT NULL,
      NAME VARCHAR2(100) NOT NULL,
      PATH VARCHAR2(200),
      ICON VARCHAR2(50),
      SORT_ORDER NUMBER NOT NULL,
      IS_ACTIVE NUMBER(1) NOT NULL,
      CREATED_AT TIMESTAMP(6) NOT NULL,
      UPDATED_AT TIMESTAMP(6) NOT NULL
    )');
  END IF;

  IF table_exists('CMH', 'NURSE_SUPPORT_NOTE') = 0 THEN
    exec_ddl('CREATE TABLE CMH.NURSE_SUPPORT_NOTE (
      ID NUMBER NOT NULL,
      ENCOUNTER_ID NUMBER NOT NULL,
      VISIT_ID NUMBER NOT NULL,
      PATIENT_ID NUMBER NOT NULL,
      SUPPORT_TYPE VARCHAR2(30) NOT NULL,
      NOTE VARCHAR2(2000),
      CREATED_BY VARCHAR2(100),
      CREATED_AT DATE NOT NULL
    )');
  END IF;

  IF table_exists('CMH', 'RECEPTION_PAYMENT') = 0 THEN
    exec_ddl('CREATE TABLE CMH.RECEPTION_PAYMENT (
      ID NUMBER NOT NULL,
      ENCOUNTER_ID NUMBER NOT NULL,
      VISIT_ID NUMBER NOT NULL,
      PATIENT_ID NUMBER NOT NULL,
      TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
      PAID_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
      STATUS VARCHAR2(20) NOT NULL,
      PAID_AT DATE,
      CREATED_BY VARCHAR2(100),
      CREATED_AT DATE NOT NULL,
      UPDATED_AT DATE
    )');
  END IF;

  IF seq_exists('CMH', 'PATIENT_ID_SEQ') = 0 THEN
    exec_ddl('CREATE SEQUENCE CMH.PATIENT_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE');
  END IF;
  IF seq_exists('CMH', 'PATIENT_MEMO_SEQ') = 0 THEN
    exec_ddl('CREATE SEQUENCE CMH.PATIENT_MEMO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE');
  END IF;
  IF seq_exists('CMH', 'PATIENT_FLAG_SEQ') = 0 THEN
    exec_ddl('CREATE SEQUENCE CMH.PATIENT_FLAG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE');
  END IF;
  IF seq_exists('CMH', 'MENU_SEQ') = 0 THEN
    exec_ddl('CREATE SEQUENCE CMH.MENU_SEQ START WITH 1 INCREMENT BY 1 NOCACHE');
  END IF;
  IF seq_exists('CMH', 'NURSE_SUPPORT_NOTE_SEQ') = 0 THEN
    exec_ddl('CREATE SEQUENCE CMH.NURSE_SUPPORT_NOTE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE');
  END IF;
  IF seq_exists('CMH', 'RECEPTION_PAYMENT_SEQ') = 0 THEN
    exec_ddl('CREATE SEQUENCE CMH.RECEPTION_PAYMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE');
  END IF;
  IF seq_exists('CMH', 'VISIT_REG_SEQ') = 0 THEN
    exec_ddl('CREATE SEQUENCE CMH.VISIT_REG_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE');
  END IF;
  IF seq_exists('CMH', 'MEDICAL_ENCOUNTER_SEQ') = 0 THEN
    exec_ddl('CREATE SEQUENCE CMH.MEDICAL_ENCOUNTER_SEQ START WITH 2000 INCREMENT BY 1 NOCACHE');
  END IF;

  IF trigger_exists('CMH', 'TRG_PATIENT_ID') = 0 THEN
    exec_ddl('CREATE OR REPLACE TRIGGER CMH.TRG_PATIENT_ID
      BEFORE INSERT ON CMH.PATIENT
      FOR EACH ROW
      WHEN (NEW.PATIENT_ID IS NULL)
      BEGIN
        :NEW.PATIENT_ID := CMH.PATIENT_ID_SEQ.NEXTVAL;
      END;');
  END IF;

  IF trigger_exists('CMH', 'TRG_PATIENT_MEMO_ID') = 0 THEN
    exec_ddl('CREATE OR REPLACE TRIGGER CMH.TRG_PATIENT_MEMO_ID
      BEFORE INSERT ON CMH.PATIENT_MEMO
      FOR EACH ROW
      WHEN (NEW.MEMO_ID IS NULL)
      BEGIN
        :NEW.MEMO_ID := CMH.PATIENT_MEMO_SEQ.NEXTVAL;
      END;');
  END IF;

  IF trigger_exists('CMH', 'TRG_PATIENT_FLAG_ID') = 0 THEN
    exec_ddl('CREATE OR REPLACE TRIGGER CMH.TRG_PATIENT_FLAG_ID
      BEFORE INSERT ON CMH.PATIENT_FLAG
      FOR EACH ROW
      WHEN (NEW.FLAG_ID IS NULL)
      BEGIN
        :NEW.FLAG_ID := CMH.PATIENT_FLAG_SEQ.NEXTVAL;
      END;');
  END IF;

  IF trigger_exists('CMH', 'TRG_MENU_ID') = 0 THEN
    exec_ddl('CREATE OR REPLACE TRIGGER CMH.TRG_MENU_ID
      BEFORE INSERT ON CMH.MENU
      FOR EACH ROW
      WHEN (NEW.ID IS NULL)
      BEGIN
        :NEW.ID := CMH.MENU_SEQ.NEXTVAL;
      END;');
  END IF;

  IF trigger_exists('CMH', 'TRG_NURSE_SUPPORT_NOTE_ID') = 0 THEN
    exec_ddl('CREATE OR REPLACE TRIGGER CMH.TRG_NURSE_SUPPORT_NOTE_ID
      BEFORE INSERT ON CMH.NURSE_SUPPORT_NOTE
      FOR EACH ROW
      WHEN (NEW.ID IS NULL)
      BEGIN
        :NEW.ID := CMH.NURSE_SUPPORT_NOTE_SEQ.NEXTVAL;
      END;');
  END IF;

  IF trigger_exists('CMH', 'TRG_RECEPTION_PAYMENT_ID') = 0 THEN
    exec_ddl('CREATE OR REPLACE TRIGGER CMH.TRG_RECEPTION_PAYMENT_ID
      BEFORE INSERT ON CMH.RECEPTION_PAYMENT
      FOR EACH ROW
      WHEN (NEW.ID IS NULL)
      BEGIN
        :NEW.ID := CMH.RECEPTION_PAYMENT_SEQ.NEXTVAL;
      END;');
  END IF;

  COMMIT;
END;
/

DECLARE
  v_patient_cnt NUMBER;
BEGIN
  MERGE INTO CMH.PATIENT p
  USING (
    SELECT patient_id,
           MAX(patient_no) AS patient_no,
           MAX(patient_name) AS patient_name,
           MAX(patient_phone) AS patient_phone
      FROM (
        SELECT v.patient_id, v.patient_no, v.patient_name, v.patient_phone
          FROM CMH.VISIT_REG v
        UNION ALL
        SELECT e.patient_id, e.patient_no, e.patient_name, CAST(NULL AS VARCHAR2(20)) AS patient_phone
          FROM CMH.MEDICAL_ENCOUNTER e
      ) s
     WHERE patient_id IS NOT NULL
     GROUP BY patient_id
  ) src
  ON (p.PATIENT_ID = src.patient_id)
  WHEN MATCHED THEN
    UPDATE SET
      p.PATIENT_NO = NVL(p.PATIENT_NO, src.patient_no),
      p.NAME = NVL(p.NAME, NVL(src.patient_name, 'PATIENT-' || TO_CHAR(src.patient_id))),
      p.PHONE = NVL(p.PHONE, src.patient_phone),
      p.UPDATED_AT = SYSDATE
  WHEN NOT MATCHED THEN
    INSERT (PATIENT_ID, PATIENT_NO, NAME, PHONE, IS_FOREIGNER, CONTACT_PRIORITY, STATUS_CODE, IS_VIP, CREATED_AT, UPDATED_AT)
    VALUES (src.patient_id, src.patient_no, NVL(src.patient_name, 'PATIENT-' || TO_CHAR(src.patient_id)), src.patient_phone, 0, 'PATIENT', 'ACTIVE', 0, SYSDATE, SYSDATE);

  INSERT INTO CMH.PATIENT (PATIENT_ID, PATIENT_NO, NAME, GENDER, BIRTH_DATE, PHONE, IS_FOREIGNER, CONTACT_PRIORITY, STATUS_CODE, IS_VIP, CREATED_AT, UPDATED_AT)
  SELECT 1, 'P000001', 'Hong Gil Dong', 'M', DATE '1990-01-10', '010-1111-1111', 0, 'PATIENT', 'ACTIVE', 0, SYSDATE, SYSDATE FROM dual
  WHERE NOT EXISTS (SELECT 1 FROM CMH.PATIENT WHERE PATIENT_ID = 1);

  INSERT INTO CMH.PATIENT (PATIENT_ID, PATIENT_NO, NAME, GENDER, BIRTH_DATE, PHONE, IS_FOREIGNER, CONTACT_PRIORITY, STATUS_CODE, IS_VIP, CREATED_AT, UPDATED_AT)
  SELECT 2, 'P000002', 'Kim Young Hee', 'F', DATE '1987-06-21', '010-2222-2222', 0, 'PATIENT', 'ACTIVE', 0, SYSDATE, SYSDATE FROM dual
  WHERE NOT EXISTS (SELECT 1 FROM CMH.PATIENT WHERE PATIENT_ID = 2);

  INSERT INTO CMH.PATIENT (PATIENT_ID, PATIENT_NO, NAME, GENDER, BIRTH_DATE, PHONE, IS_FOREIGNER, CONTACT_PRIORITY, STATUS_CODE, IS_VIP, CREATED_AT, UPDATED_AT)
  SELECT 3, 'P000003', 'Lee Nurse', 'F', DATE '1995-02-14', '010-3333-3333', 0, 'PATIENT', 'ACTIVE', 0, SYSDATE, SYSDATE FROM dual
  WHERE NOT EXISTS (SELECT 1 FROM CMH.PATIENT WHERE PATIENT_ID = 3);

  INSERT INTO CMH.VISIT_REG (
    ID, VISIT_NO, PATIENT_ID, PATIENT_NO, PATIENT_NAME, PATIENT_PHONE,
    VISIT_TYPE, STATUS, DEPT_CODE, DOCTOR_ID, PRIORITY_YN, QUEUE_NO,
    CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
  )
  SELECT
    e.VISIT_ID,
    'AUTO-V-' || LPAD(TO_CHAR(e.VISIT_ID), 6, '0'),
    e.PATIENT_ID,
    e.PATIENT_NO,
    NVL(e.PATIENT_NAME, p.NAME),
    p.PHONE,
    'VISIT',
    NVL(e.STATUS, 'WAITING'),
    NVL(e.DEPT_CODE, 'GENERAL'),
    e.DOCTOR_ID,
    0,
    NULL,
    'bootstrap',
    'bootstrap',
    NVL(e.CREATED_AT, SYSDATE),
    SYSDATE
  FROM CMH.MEDICAL_ENCOUNTER e
  LEFT JOIN CMH.PATIENT p ON p.PATIENT_ID = e.PATIENT_ID
  WHERE NOT EXISTS (SELECT 1 FROM CMH.VISIT_REG v WHERE v.ID = e.VISIT_ID);

  UPDATE CMH.MEDICAL_ENCOUNTER e
     SET e.PATIENT_ID = (SELECT v.PATIENT_ID FROM CMH.VISIT_REG v WHERE v.ID = e.VISIT_ID),
         e.PATIENT_NO = NVL(e.PATIENT_NO, (SELECT v.PATIENT_NO FROM CMH.VISIT_REG v WHERE v.ID = e.VISIT_ID)),
         e.PATIENT_NAME = NVL(e.PATIENT_NAME, (SELECT v.PATIENT_NAME FROM CMH.VISIT_REG v WHERE v.ID = e.VISIT_ID)),
         e.UPDATED_AT = SYSDATE
   WHERE EXISTS (SELECT 1 FROM CMH.VISIT_REG v WHERE v.ID = e.VISIT_ID)
     AND (e.PATIENT_ID IS NULL OR e.PATIENT_ID != (SELECT v.PATIENT_ID FROM CMH.VISIT_REG v WHERE v.ID = e.VISIT_ID)
       OR e.PATIENT_NAME IS NULL OR e.PATIENT_NO IS NULL);

  INSERT INTO CMH.MEDICAL_ENCOUNTER (
    ID, VISIT_ID, PATIENT_ID, PATIENT_NO, PATIENT_NAME, DOCTOR_ID, DEPT_CODE,
    STATUS, MEMO, IS_ACTIVE, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
  )
  SELECT
    CMH.MEDICAL_ENCOUNTER_SEQ.NEXTVAL,
    v.ID,
    v.PATIENT_ID,
    v.PATIENT_NO,
    v.PATIENT_NAME,
    v.DOCTOR_ID,
    v.DEPT_CODE,
    CASE WHEN UPPER(NVL(v.STATUS, 'WAITING')) IN ('IN_PROGRESS', 'WAITING', 'DONE') THEN UPPER(v.STATUS) ELSE 'WAITING' END,
    'Auto-generated from visit flow',
    'Y',
    'bootstrap',
    'bootstrap',
    NVL(v.CREATED_AT, SYSDATE),
    SYSDATE
  FROM CMH.VISIT_REG v
  WHERE (UPPER(NVL(v.VISIT_TYPE, 'VISIT')) = 'VISIT' OR v.STARTED_AT IS NOT NULL)
    AND NOT EXISTS (SELECT 1 FROM CMH.MEDICAL_ENCOUNTER e WHERE e.VISIT_ID = v.ID);

  SELECT COUNT(*) INTO v_patient_cnt FROM CMH.PATIENT;
  IF v_patient_cnt > 0 THEN
    INSERT INTO CMH.PATIENT_MEMO (MEMO_ID, PATIENT_ID, MEMO, CREATED_BY, CREATED_AT, UPDATED_AT)
    SELECT CMH.PATIENT_MEMO_SEQ.NEXTVAL, p.PATIENT_ID, 'Initial support memo for patient ' || p.PATIENT_ID, 'bootstrap', SYSDATE, SYSDATE
      FROM CMH.PATIENT p
     WHERE p.PATIENT_ID IN (SELECT patient_id FROM (SELECT PATIENT_ID FROM CMH.PATIENT) WHERE ROWNUM <= 3)
       AND NOT EXISTS (SELECT 1 FROM CMH.PATIENT_MEMO m WHERE m.PATIENT_ID = p.PATIENT_ID);

    INSERT INTO CMH.PATIENT_FLAG (FLAG_ID, PATIENT_ID, FLAG_TYPE, NOTE, ACTIVE_YN, CREATED_BY, CREATED_AT, UPDATED_AT)
    SELECT CMH.PATIENT_FLAG_SEQ.NEXTVAL, p.PATIENT_ID, 'FALL_RISK', 'Auto-created risk flag', 1, 'bootstrap', SYSDATE, SYSDATE
      FROM CMH.PATIENT p
     WHERE p.PATIENT_ID IN (SELECT patient_id FROM (SELECT PATIENT_ID FROM CMH.PATIENT) WHERE ROWNUM <= 2)
       AND NOT EXISTS (SELECT 1 FROM CMH.PATIENT_FLAG f WHERE f.PATIENT_ID = p.PATIENT_ID);
  END IF;

  INSERT INTO CMH.NURSE_SUPPORT_NOTE (
    ID, ENCOUNTER_ID, VISIT_ID, PATIENT_ID, SUPPORT_TYPE, NOTE, CREATED_BY, CREATED_AT
  )
  SELECT
    CMH.NURSE_SUPPORT_NOTE_SEQ.NEXTVAL,
    e.ID,
    e.VISIT_ID,
    e.PATIENT_ID,
    'SBAR',
    'Baseline support note linked to encounter ' || e.ID,
    'bootstrap',
    SYSDATE
  FROM CMH.MEDICAL_ENCOUNTER e
  WHERE NOT EXISTS (SELECT 1 FROM CMH.NURSE_SUPPORT_NOTE n WHERE n.ENCOUNTER_ID = e.ID)
    AND e.ROWID IN (SELECT rid FROM (SELECT ROWID rid FROM CMH.MEDICAL_ENCOUNTER) WHERE ROWNUM <= 5);

  INSERT INTO CMH.RECEPTION_PAYMENT (
    ID, ENCOUNTER_ID, VISIT_ID, PATIENT_ID, TOTAL_AMOUNT, PAID_AMOUNT, STATUS, PAID_AT, CREATED_BY, CREATED_AT, UPDATED_AT
  )
  SELECT
    CMH.RECEPTION_PAYMENT_SEQ.NEXTVAL,
    e.ID,
    e.VISIT_ID,
    e.PATIENT_ID,
    25000,
    CASE WHEN UPPER(NVL(e.STATUS, 'WAITING')) = 'DONE' THEN 25000 ELSE 0 END,
    CASE WHEN UPPER(NVL(e.STATUS, 'WAITING')) = 'DONE' THEN 'PAID' ELSE 'UNPAID' END,
    CASE WHEN UPPER(NVL(e.STATUS, 'WAITING')) = 'DONE' THEN SYSDATE ELSE NULL END,
    'bootstrap',
    SYSDATE,
    SYSDATE
  FROM CMH.MEDICAL_ENCOUNTER e
  WHERE NOT EXISTS (SELECT 1 FROM CMH.RECEPTION_PAYMENT p WHERE p.ENCOUNTER_ID = e.ID)
    AND e.ROWID IN (SELECT rid FROM (SELECT ROWID rid FROM CMH.MEDICAL_ENCOUNTER) WHERE ROWNUM <= 10);

  COMMIT;
END;
/

DECLARE
  FUNCTION constraint_exists(p_owner IN VARCHAR2, p_table IN VARCHAR2, p_name IN VARCHAR2) RETURN NUMBER IS
    v_cnt NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_cnt
      FROM ALL_CONSTRAINTS
     WHERE OWNER = UPPER(p_owner)
       AND TABLE_NAME = UPPER(p_table)
       AND CONSTRAINT_NAME = UPPER(p_name);
    RETURN v_cnt;
  END;

  FUNCTION has_primary_key(p_owner IN VARCHAR2, p_table IN VARCHAR2) RETURN NUMBER IS
    v_cnt NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_cnt
      FROM ALL_CONSTRAINTS
     WHERE OWNER = UPPER(p_owner)
       AND TABLE_NAME = UPPER(p_table)
       AND CONSTRAINT_TYPE = 'P';
    RETURN v_cnt;
  END;
BEGIN
  MERGE INTO CMH.PATIENT p
  USING (
    SELECT patient_id,
           MAX(patient_no) AS patient_no,
           MAX(patient_name) AS patient_name,
           MAX(patient_phone) AS patient_phone
      FROM CMH.VISIT_REG
     WHERE patient_id IS NOT NULL
     GROUP BY patient_id
  ) src
  ON (p.PATIENT_ID = src.patient_id)
  WHEN MATCHED THEN
    UPDATE SET p.PATIENT_NO = NVL(p.PATIENT_NO, src.patient_no),
               p.NAME = NVL(p.NAME, NVL(src.patient_name, 'PATIENT-' || TO_CHAR(src.patient_id))),
               p.PHONE = NVL(p.PHONE, src.patient_phone),
               p.UPDATED_AT = SYSDATE
  WHEN NOT MATCHED THEN
    INSERT (PATIENT_ID, PATIENT_NO, NAME, PHONE, IS_FOREIGNER, CONTACT_PRIORITY, STATUS_CODE, IS_VIP, CREATED_AT, UPDATED_AT)
    VALUES (src.patient_id, src.patient_no, NVL(src.patient_name, 'PATIENT-' || TO_CHAR(src.patient_id)), src.patient_phone, 0, 'PATIENT', 'ACTIVE', 0, SYSDATE, SYSDATE);

  INSERT INTO CMH.VISIT_REG (
    ID, VISIT_NO, PATIENT_ID, PATIENT_NO, PATIENT_NAME, PATIENT_PHONE,
    VISIT_TYPE, STATUS, DEPT_CODE, DOCTOR_ID, PRIORITY_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
  )
  SELECT
    e.VISIT_ID,
    'AUTO-V-' || LPAD(TO_CHAR(e.VISIT_ID), 6, '0'),
    e.PATIENT_ID,
    e.PATIENT_NO,
    NVL(e.PATIENT_NAME, p.NAME),
    p.PHONE,
    'VISIT',
    NVL(e.STATUS, 'WAITING'),
    NVL(e.DEPT_CODE, 'GENERAL'),
    e.DOCTOR_ID,
    0,
    'bootstrap',
    'bootstrap',
    NVL(e.CREATED_AT, SYSDATE),
    SYSDATE
  FROM CMH.MEDICAL_ENCOUNTER e
  LEFT JOIN CMH.PATIENT p ON p.PATIENT_ID = e.PATIENT_ID
  WHERE NOT EXISTS (SELECT 1 FROM CMH.VISIT_REG v WHERE v.ID = e.VISIT_ID);

  IF has_primary_key('CMH', 'PATIENT') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.PATIENT ADD CONSTRAINT PK_PATIENT PRIMARY KEY (PATIENT_ID)';
  END IF;
  IF has_primary_key('CMH', 'PATIENT_MEMO') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.PATIENT_MEMO ADD CONSTRAINT PK_PATIENT_MEMO PRIMARY KEY (MEMO_ID)';
  END IF;
  IF has_primary_key('CMH', 'PATIENT_FLAG') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.PATIENT_FLAG ADD CONSTRAINT PK_PATIENT_FLAG PRIMARY KEY (FLAG_ID)';
  END IF;
  IF has_primary_key('CMH', 'MENU') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.MENU ADD CONSTRAINT PK_MENU PRIMARY KEY (ID)';
  END IF;
  IF has_primary_key('CMH', 'RECEPTION_PAYMENT') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.RECEPTION_PAYMENT ADD CONSTRAINT PK_RECEPTION_PAYMENT PRIMARY KEY (ID)';
  END IF;
  IF has_primary_key('CMH', 'NURSE_SUPPORT_NOTE') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.NURSE_SUPPORT_NOTE ADD CONSTRAINT PK_NURSE_SUPPORT_NOTE PRIMARY KEY (ID)';
  END IF;
  IF has_primary_key('CMH', 'VISIT_REG') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.VISIT_REG ADD CONSTRAINT PK_VISIT_REG PRIMARY KEY (ID)';
  END IF;
  IF has_primary_key('CMH', 'MEDICAL_ENCOUNTER') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.MEDICAL_ENCOUNTER ADD CONSTRAINT PK_MEDICAL_ENCOUNTER PRIMARY KEY (ID)';
  END IF;

  IF constraint_exists('CMH', 'VISIT_REG', 'FK_VISIT_PATIENT') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.VISIT_REG ADD CONSTRAINT FK_VISIT_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES CMH.PATIENT(PATIENT_ID)';
  END IF;
  IF constraint_exists('CMH', 'MEDICAL_ENCOUNTER', 'FK_MED_ENC_VISIT') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.MEDICAL_ENCOUNTER ADD CONSTRAINT FK_MED_ENC_VISIT FOREIGN KEY (VISIT_ID) REFERENCES CMH.VISIT_REG(ID)';
  END IF;
  IF constraint_exists('CMH', 'MEDICAL_ENCOUNTER', 'FK_MED_ENC_PATIENT') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.MEDICAL_ENCOUNTER ADD CONSTRAINT FK_MED_ENC_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES CMH.PATIENT(PATIENT_ID)';
  END IF;
  IF constraint_exists('CMH', 'PATIENT_MEMO', 'FK_PATIENT_MEMO_PATIENT') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.PATIENT_MEMO ADD CONSTRAINT FK_PATIENT_MEMO_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES CMH.PATIENT(PATIENT_ID)';
  END IF;
  IF constraint_exists('CMH', 'PATIENT_FLAG', 'FK_PATIENT_FLAG_PATIENT') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.PATIENT_FLAG ADD CONSTRAINT FK_PATIENT_FLAG_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES CMH.PATIENT(PATIENT_ID)';
  END IF;
  IF constraint_exists('CMH', 'NURSE_SUPPORT_NOTE', 'FK_NURSE_NOTE_ENC') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.NURSE_SUPPORT_NOTE ADD CONSTRAINT FK_NURSE_NOTE_ENC FOREIGN KEY (ENCOUNTER_ID) REFERENCES CMH.MEDICAL_ENCOUNTER(ID)';
  END IF;
  IF constraint_exists('CMH', 'NURSE_SUPPORT_NOTE', 'FK_NURSE_NOTE_VISIT') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.NURSE_SUPPORT_NOTE ADD CONSTRAINT FK_NURSE_NOTE_VISIT FOREIGN KEY (VISIT_ID) REFERENCES CMH.VISIT_REG(ID)';
  END IF;
  IF constraint_exists('CMH', 'NURSE_SUPPORT_NOTE', 'FK_NURSE_NOTE_PATIENT') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.NURSE_SUPPORT_NOTE ADD CONSTRAINT FK_NURSE_NOTE_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES CMH.PATIENT(PATIENT_ID)';
  END IF;
  IF constraint_exists('CMH', 'RECEPTION_PAYMENT', 'FK_PAY_ENC') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.RECEPTION_PAYMENT ADD CONSTRAINT FK_PAY_ENC FOREIGN KEY (ENCOUNTER_ID) REFERENCES CMH.MEDICAL_ENCOUNTER(ID)';
  END IF;
  IF constraint_exists('CMH', 'RECEPTION_PAYMENT', 'FK_PAY_VISIT') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.RECEPTION_PAYMENT ADD CONSTRAINT FK_PAY_VISIT FOREIGN KEY (VISIT_ID) REFERENCES CMH.VISIT_REG(ID)';
  END IF;
  IF constraint_exists('CMH', 'RECEPTION_PAYMENT', 'FK_PAY_PATIENT') = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMH.RECEPTION_PAYMENT ADD CONSTRAINT FK_PAY_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES CMH.PATIENT(PATIENT_ID)';
  END IF;

  COMMIT;
END;
/
