DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM ALL_TAB_COLUMNS
     WHERE OWNER = 'CMH'
       AND TABLE_NAME = 'AUTH_SESSION'
       AND COLUMN_NAME = 'REFRESH_TOKEN_JTI';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE CMH.AUTH_SESSION ADD (REFRESH_TOKEN_JTI VARCHAR2(36))';
    END IF;
END;
/
