DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM ALL_TAB_COLUMNS
     WHERE OWNER = 'CMH'
       AND TABLE_NAME = 'AUTH_SESSION'
       AND COLUMN_NAME = 'ACCESS_TOKEN_JTI';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE CMH.AUTH_SESSION DROP COLUMN ACCESS_TOKEN_JTI';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM ALL_TAB_COLUMNS
     WHERE OWNER = 'CMH'
       AND TABLE_NAME = 'AUTH_SESSION'
       AND COLUMN_NAME = 'REFRESH_TOKEN_JTI';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE CMH.AUTH_SESSION DROP COLUMN REFRESH_TOKEN_JTI';
    END IF;
    SELECT COUNT(*)
      INTO v_count
      FROM ALL_TAB_COLUMNS
     WHERE OWNER = 'HOSPITAL'
       AND TABLE_NAME = 'AUTH_SESSION'
       AND COLUMN_NAME = 'ACCESS_TOKEN_JTI';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.AUTH_SESSION DROP COLUMN ACCESS_TOKEN_JTI';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM ALL_TAB_COLUMNS
     WHERE OWNER = 'HOSPITAL'
       AND TABLE_NAME = 'AUTH_SESSION'
       AND COLUMN_NAME = 'REFRESH_TOKEN_JTI';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.AUTH_SESSION DROP COLUMN REFRESH_TOKEN_JTI';
    END IF;
END;
/
