-- Rebuild sidebar menus for the current frontend routes.
-- This script resets role-based menu visibility to "view only" for every role.

DELETE FROM CMH.AUTH_ROLE_MENU_PERMISSION;
DELETE FROM CMH.MENU;

INSERT INTO CMH.MENU (MENU_ID, PARENT_ID, CODE, NAME, PATH, ICON, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (1, NULL, 'DASHBOARD', '대시보드', '/', 'Home', 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO CMH.MENU VALUES (2, NULL, 'PATIENT', '환자 관리', NULL, 'People', 2, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (5, 2, 'PATIENT_LIST', '환자 목록', '/patient/list', NULL, 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1007, 2, 'PATIENT_CREATE', '환자 등록', '/patient/create', NULL, 2, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (6, 2, 'PATIENT_INSURANCE', '보험 관리', '/patient/insurance/list', NULL, 3, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1008, 2, 'PATIENT_CONSENT', '동의서 관리', '/patient/consent/list', NULL, 4, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO CMH.MENU VALUES (1000, NULL, 'RECEPTION', '접수 관리', NULL, 'FactCheck', 3, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1001, 1000, 'RECEPTION_DASHBOARD', '접수 대시보드', '/reception/dashboard', NULL, 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (16, 1000, 'RECEPTION_OUTPATIENT', '외래 접수', '/reception/outpatient/list', NULL, 2, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1002, 1000, 'RECEPTION_APPOINTMENT', '예약 접수', '/reception/appointment/list', NULL, 3, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (13, 1000, 'RECEPTION_EMERGENCY', '응급 접수', '/reception/emergency/list', NULL, 4, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (14, 1000, 'RECEPTION_ADMISSION', '입원 접수', '/reception/admission/list', NULL, 5, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO CMH.MENU VALUES (1300, NULL, 'CLINICAL', '진료', '/clinical', 'MedicalServices', 4, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO CMH.MENU VALUES (1400, NULL, 'MEDICAL_SUPPORT', '진료 지원', NULL, 'TaskAlt', 5, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1401, 1400, 'MEDICAL_SUPPORT_DASHBOARD', '진료 지원 대시보드', '/medical_support/dashboard', NULL, 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1404, 1400, 'MEDICAL_SUPPORT_IMAGING', '영상 지원', '/medical_support/imaging', NULL, 2, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1405, 1400, 'NURSING_RECORD', '간호 기록', '/medical_support/record/list', NULL, 3, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1406, 1400, 'SPECIMEN', '검체 관리', '/medical_support/specimen/list', NULL, 4, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO CMH.MENU VALUES (1100, NULL, 'BILLING', '청구', NULL, 'Description', 6, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1101, 1100, 'BILLING_DASHBOARD', '청구 메인', '/billing', NULL, 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1102, 1100, 'BILLING_LIST', '청구 목록', '/billing/list', NULL, 2, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1103, 1100, 'RECEIPT_DASHBOARD', '수납 대시보드', '/receipt/dashboard', NULL, 3, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO CMH.MENU VALUES (1600, NULL, 'STAFF', '스탭', NULL, 'People', 7, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1610, 1600, 'STAFF_HOME', '스탭 메인', '/staff', NULL, 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1630, 1600, 'STAFF_DASHBOARD', '의료진 관리', '/staff/dashboard', NULL, 2, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1620, 1600, 'STAFF_JOIN_LIST', '스탭 목록', '/staff/join/list', NULL, 3, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1631, 1600, 'STAFF_DEPT', '부서 관리', '/staff/dept', NULL, 4, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1632, 1600, 'STAFF_POSITION', '직책 관리', '/staff/position', NULL, 5, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO CMH.MENU VALUES (1500, NULL, 'ADMIN', '관리', NULL, 'Policy', 8, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1501, 1500, 'ADMIN_CODES', '코드 관리', '/admin/codes', NULL, 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1502, 1500, 'ADMIN_COMMON', '공통 관리', '/admin/common', NULL, 2, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1503, 1500, 'ADMIN_PERMISSIONS', '권한 관리', '/admin/permissions', NULL, 3, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO CMH.MENU VALUES (1504, 1500, 'ADMIN_REGISTER_REQUESTS', '가입 승인 관리', '/admin/register-requests', NULL, 4, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO CMH.AUTH_ROLE_MENU_PERMISSION (
    ROLE_CODE,
    MENU_ID,
    CAN_VIEW,
    CAN_CREATE,
    CAN_UPDATE,
    CAN_DELETE
)
SELECT r.ROLE_CODE,
       m.MENU_ID,
       'Y' AS CAN_VIEW,
       'N' AS CAN_CREATE,
       'N' AS CAN_UPDATE,
       'N' AS CAN_DELETE
FROM CMH.AUTH_ROLE r
CROSS JOIN CMH.MENU m
WHERE m.IS_ACTIVE = 'Y';

UPDATE CMH.AUTH_ROLE_MENU_PERMISSION
   SET CAN_VIEW = 'N'
 WHERE MENU_ID = 1504
   AND ROLE_CODE <> 'ADMIN';

COMMIT;
