ALTER TABLE CLINICAL_ORDER ADD LEGACY_PRESCRIPTION_ID NUMBER(19);
CREATE UNIQUE INDEX UX_CL_ORDER_LEGACY_RX ON CLINICAL_ORDER (LEGACY_PRESCRIPTION_ID);

ALTER TABLE CLINICAL_ORDER_ITEM ADD ITEM_NAME VARCHAR2(600);
ALTER TABLE CLINICAL_ORDER_ITEM ADD ITEM_DOSAGE VARCHAR2(200);
