CREATE SEQUENCE CL_VSOAP_RX_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE VISIT_SOAP_PRESCRIPTION (
    PRESCRIPTION_ID   NUMBER        NOT NULL,
    VISIT_ID          NUMBER        NOT NULL,
    MEDICATION_NAME   VARCHAR2(600),
    DOSAGE            VARCHAR2(200),
    FREQUENCY         VARCHAR2(100),
    DAYS              VARCHAR2(50),
    CREATED_AT        TIMESTAMP     NOT NULL,
    UPDATED_AT        TIMESTAMP     NOT NULL,
    CONSTRAINT PK_VISIT_SOAP_PRESCRIPTION PRIMARY KEY (PRESCRIPTION_ID)
);

CREATE INDEX IDX_VSPR_VISIT ON VISIT_SOAP_PRESCRIPTION (VISIT_ID, PRESCRIPTION_ID);
