CREATE SEQUENCE CL_VSOAP_DX_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE VISIT_SOAP_DIAGNOSIS (
    DIAGNOSIS_ID   NUMBER        NOT NULL,
    VISIT_ID       NUMBER        NOT NULL,
    DX_CODE        VARCHAR2(50),
    DX_NAME        VARCHAR2(500),
    MAIN_YN        CHAR(1)       DEFAULT 'N' NOT NULL,
    SORT_ORDER     NUMBER(10)    DEFAULT 0 NOT NULL,
    CREATED_AT     TIMESTAMP     NOT NULL,
    UPDATED_AT     TIMESTAMP     NOT NULL,
    CONSTRAINT PK_VISIT_SOAP_DIAGNOSIS PRIMARY KEY (DIAGNOSIS_ID)
);

CREATE INDEX IDX_VSD_VISIT ON VISIT_SOAP_DIAGNOSIS (VISIT_ID, SORT_ORDER, DIAGNOSIS_ID);
