spring.application.name=Employee


server.port=8022
server.address=0.0.0.0

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/xepdb1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.username=JCH
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:changeme}

#mybatis
mybatis.mapper-locations=classpath*:/mapper/**/*.xml
mybatis.type-aliases-package=com.staff
mybatis.configuration.map-underscore-to-camel-case=true



# =========================
# JPA
# =========================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true



# =========================
# MinIO
# =========================
minio.url=http://localhost:9000
minio.access-key=${MINIO_ACCESS_KEY:changeme}
minio.secret-key=${MINIO_SECRET_KEY:changeme}

minio.bucket=staff-profile
minio.public-base-url=http://localhost:9000


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
